### ISSUE TITLE
electron.d.ts does not work with @types/node v14.14.5

### ISSUE THREAD

**Issue by sandersn** [electron/electron#26224]
`@types/node` recently [added](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49045) `traceDeprecation` to the `Process` class. Previously, electron's type polyfilled this declaration. Now that it's in node, the declarations must match exactly, but electron's declaration says the property is optional. See the discussion in the linked PR about why it's not.

The fix is to make the property required in electron as well. I'll put a PR up shortly.

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.1.12
* **Operating System:**
  * Ubuntu 20.04.1 x64
* **Last Known Working Electron version:**
  * 6.1.12, broken in `@types/node@14.14.4`

### Expected Behavior
No compile error with typescript

### Actual Behavior

```
node_modules/electron/electron.d.ts(10710,5): error TS2687: All declarations of 'traceDeprecation' must have identical modifiers.
 ../node/process.d.ts(298,17): error TS2687: All declarations of 'traceDeprecation' must have identical modifiers.
../node/process.d.ts(298,17): error TS2717: Subsequent property declarations must have the same type.  Property 'traceDeprecation' must be of type 'boolean | undefined', but here has type 'boolean'.
```

From the Definitely Typed compile of `@types/electron-clipboard-extended` -- the `@types/node` path is usually `node_modules/@types/node/process.d.ts`.

### To Reproduce
npm install electron@6 @types/node@latest
touch foo.ts
tsc foo.ts

### Additional Information

This is basically the same as #21612, but the type conflict is simpler.

**Comment by sandersn** [comment]
Regenerating electron.d.ts shows that `traceDeprecation` isn't optional anymore, so I think that's all that needs to happen here. Does that happen regularly or do I need to submit a PR to make it happen?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If you're still experiencing this issue in Electron 8.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
@sandersn this is not expected to work - Electron v6 through v11 use Node.js v12 LTS. You should use a version of `@types/node` that matches the version of Node.js bundled with Electron.
