### ISSUE TITLE
windows build failure linking node.dll: v8.lib was created with an older compiler than other objects

### ISSUE THREAD

**Issue by bughit** [electron/electron#12898]
* Electron Version: master (e79751c8d450249b19c764f79c9d741f2662b074)
* Operating System (Platform and Version): win7 sp1 x64

**Expected Behavior**
should build

**Actual behavior**
```
[9/205] LINK_EMBED(DLL) node.dll
FAILED: C:\Python27\python.exe gyp-win-tool link-with-manifests environment.x86 True node.dll "C:\Python27\python.exe gyp-win-tool l
ink-wrapper environment.x86 False link.exe /nologo /IMPLIB:node.dll.lib /DLL /OUT:node.dll @node.dll.rsp" 2 mt.exe rc.exe "obj\vendo
r\node\node_lib.node.dll.intermediate.manifest" obj\vendor\node\node_lib.node.dll.generated.manifest
fatal error C1047: The object or library file 'C:\src\electron\vendor\download\libchromiumcontent\static_library\v8.lib'
was created with an older compiler than other objects; rebuild old objects and libraries
LINK : fatal error LNK1257: code generation failed
Traceback (most recent call last):
  File "gyp-win-tool", line 323, in <module>
    sys.exit(main(sys.argv[1:]))
  File "gyp-win-tool", line 29, in main
    exit_code = executor.Dispatch(args)
  File "gyp-win-tool", line 71, in Dispatch
    return getattr(self, method)(*args[1:])
  File "gyp-win-tool", line 179, in ExecLinkWithManifests
    subprocess.check_call(ldcmd + add_to_ld)
  File "C:\Python27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /IMP
LIB:node.dll.lib /DLL /OUT:node.dll @node.dll.rsp node.dll.manifest.res' returned non-zero exit status 1257
[9/205] CXX obj\atom\browser\electron_lib.native_window_views.obj
ninja: build stopped: subcommand failed.
```

**To Reproduce**

do a clean windows 32bit build with VS2017 15.7.1

**Additional Information**

https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1047

> C1047 is caused when object files or libraries built with /LTCG are linked together, but where those object files or libraries are built with different versions of the Visual C++ toolset. 

looks like /LTCG is the culprit

https://docs.microsoft.com/en-us/cpp/build/reference/ltcg-link-time-code-generation
https://docs.microsoft.com/en-us/cpp/build/reference/gl-whole-program-optimization

different vs2017 minor versions can't be installed side by side, so requiring a specific version does not seem practical

**Comment by bughit** [comment]
@felixrieseberg We discussed briefly vs2017 version requirements in #12372, what are your thoughts on this?

**Comment by MarshallOfSound** [comment]
@bughit You're gonna be linking with a version of the C++ toolset that is incompatible with the C++ toolset that libcc is pre-built with.  Either downgrade VS to match that version or build libcc yourself locally.

**Comment by bughit** [comment]
@MarshallOfSound @felixrieseberg 

How can one tell what version of visual studio is needed?

**Comment by bughit** [comment]
@jkleinsc

How can one tell what version of visual studio is needed?  Until #13593 15.6 was needed, now 15.7.

**Comment by jkleinsc** [comment]
@bughit it should be in https://electronjs.org/docs/development/build-instructions-windows.  I have a PR #13663 to update for master/3-0-x

**Comment by bughit** [comment]
@jkleinsc "15.7.2 or higher" will no longer be correct when 15.8 is released, before you move to it. It should be ">= 15.7.2 < 15.8"

also it's worth linking to https://docs.microsoft.com/en-us/visualstudio/productinfo/installing-an-earlier-release-of-vs2017 which will be needed after 15.8

**Comment by adamkidder** [comment]
This is now the case with VS 15.8 out. Following the official Electron Windows build instructions results in this error message.

I'd recommend changing the Windows build documentation to list the VS major version that is required.

**Comment by adamkidder** [comment]
I get the same error with Visual Studio 15.7.6 installed as well.

What is the correct version of Visual Studio to use?

**Comment by bughit** [comment]
@jkleinsc 

you could put the vs version in the lib archive as a file that would be auto generated at lib build time, or you could auto publish this info somewhere. This should be automated since that's more reliable than someone manually updating docs.

**Comment by jkleinsc** [comment]
For 3-0-x we had to revert back to VS2017 15.4.5:
https://github.com/electron/libchromiumcontent/pull/642

We need to update the docs to reflect that for 3-0-x you need to use this specific version

As soon as #14097 lands, master will not have that restriction because we are switching to a GN build that doesn't use libchromiumcontent in the same way.

**Comment by jkleinsc** [comment]
Resolved via #14476
