### ISSUE TITLE
Support standard C++ headers / libs when building addons for Electron

### ISSUE THREAD

**Issue by antonycourtney** [electron/electron#8481]
* Electron version:  1.4.15
* Operating system: macOS Sierra 10.12.2

### Expected behavior

On my system (A Mac running macOS Sierra 10.12.2), including a standard C++ 11 header file such as `<regex>` using

```cpp
#include <regex>
```
in a C++ source file for a Node addon compiles with no warnings or errors when using node-gyp to build for node.js v7.1.0.

I would expect this addon to also compile without warnings or errors when using node-gyp in the manner recommended by [Using Native Node Modules](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md) to build for electron.

### Actual behavior

Rebuilding this addon for electron.js following the instructions in [Using Native Node Modules](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md) fails with an error indicating the the standard C++ header file `<regex>` is not found:

```
[...]
../hello.cc:2:10: fatal error: 'regex' file not found
#include <regex>
         ^
1 error generated.
make: *** [Release/obj.target/hello/hello.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
```

### How to reproduce

I have created a github repo with a minimal reproducible example, instructions to reproduce, 
an analysis of the configuration file diff between the Electron fork of Node and Node.js that I believe is causing the problem, and a temporary workaround for the issue:

[https://github.com/antonycourtney/electron-cpp-addon](https://github.com/antonycourtney/electron-cpp-addon)

**Comment by kevinsawicki** [comment]
I think this might be fixed once #8406 gets released.

Looks like that `CLANG_CXX_LIBRARY ` difference you noted in the `common.gypi`  file was added in https://github.com/nodejs/node/pull/8317.

Electron 1.4.15 included the `common.gypi` from Node 6.5, and Electron 1.5 will be built on Node 7.4 which should have that version of `common.gypi`.

**Comment by kevinsawicki** [comment]
Tested this out on master and I was able to compile the add-on using Electron 1.5.

Will leave this open until 1.5.0 hits beta and then will check back in.

**Comment by antonycourtney** [comment]
@kevinsawicki Thanks

**Comment by kevinsawicki** [comment]
@antonycourtney 1.5.0 is out now, can you try building against it?

**Comment by antonycourtney** [comment]
@kevinsawicki Just downloaded and installed 1.5.0.  Unfortunately I still get the same error, plus a large number of deprecation warnings:

```
$ electron --version
v1.5.0
$ HOME=~/.electron-gyp node-gyp rebuild --target=1.5.0 --arch=x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.1.0 | darwin | x64
gyp info spawn /Users/antony/anaconda/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/antony/home/src/js/electron-cpp-addon/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/antony/home/src/js/electron-cpp-addon',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/hello/hello.o
In file included from ../hello.cc:1:
In file included from ../node_modules/nan/nan.h:47:
/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0/src/node.h:255:10: warning:
      'FatalException' is deprecated [-Wdeprecated-declarations]
  return FatalException(v8::Isolate::GetCurrent(), try_catch);
         ^
/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0/src/node.h:250:18: note:
      'FatalException' has been explicitly marked deprecated here
NODE_EXTERN void FatalException(v8::Isolate* isolate,
                 ^
/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0/src/node.h:281:10: warning:
      'Encode' is deprecated [-Wdeprecated-declarations]
  return Encode(isolate, static_cast<const char*>(buf), len, encoding);
         ^
/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0/src/node.h:259:34: note:
      'Encode' has been explicitly marked deprecated here
NODE_EXTERN v8::Local<v8::Value> Encode(v8::Isolate* isolate,
                                 ^
/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0/src/node.h:292:10: warning:
      'DecodeBytes' is deprecated [-Wdeprecated-declarations]
  return DecodeBytes(v8::Isolate::GetCurrent(), val, encoding);
         ^
/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0/src/node.h:285:21: note:
      'DecodeBytes' has been explicitly marked deprecated here
NODE_EXTERN ssize_t DecodeBytes(v8::Isolate* isolate,
                    ^
/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0/src/node.h:306:10: warning:
      'DecodeWrite' is deprecated [-Wdeprecated-declarations]
  return DecodeWrite(v8::Isolate::GetCurrent(), buf, buflen, val, encoding);
         ^
/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0/src/node.h:296:21: note:
      'DecodeWrite' has been explicitly marked deprecated here
NODE_EXTERN ssize_t DecodeWrite(v8::Isolate* isolate,
                    ^
In file included from ../hello.cc:1:
In file included from ../node_modules/nan/nan.h:48:
/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0/src/node_buffer.h:37:10: warning:
      'New' is deprecated [-Wdeprecated-declarations]
  return New(v8::Isolate::GetCurrent(), string, enc);
         ^
/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0/src/node_buffer.h:31:35: note:
      'New' has been explicitly marked deprecated here
NODE_EXTERN v8::Local<v8::Object> New(v8::Isolate* isolate,
                                  ^
/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0/src/node_buffer.h:46:10: warning:
      'New' is deprecated [-Wdeprecated-declarations]
  return New(v8::Isolate::GetCurrent(), data, len);
         ^
/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0/src/node_buffer.h:41:35: note:
      'New' has been explicitly marked deprecated here
NODE_EXTERN v8::Local<v8::Object> New(v8::Isolate* isolate,
                                  ^
/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0/src/node_buffer.h:59:10: warning:
      'New' is deprecated [-Wdeprecated-declarations]
  return New(v8::Isolate::GetCurrent(), data, length, callback, hint);
         ^
/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0/src/node_buffer.h:49:35: note:
      'New' has been explicitly marked deprecated here
NODE_EXTERN v8::Local<v8::Object> New(v8::Isolate* isolate,
                                  ^
/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0/src/node_buffer.h:69:10: warning:
      'Use' is deprecated [-Wdeprecated-declarations]
  return Use(v8::Isolate::GetCurrent(), data, len);
         ^
/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0/src/node_buffer.h:64:35: note:
      'Use' has been explicitly marked deprecated here
NODE_EXTERN v8::Local<v8::Object> Use(v8::Isolate* isolate,
                                  ^
In file included from ../hello.cc:1:
../node_modules/nan/nan.h:691:26: warning: 'New' is deprecated
      [-Wdeprecated-declarations]
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, length, callback,
                         ^
/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0/src/node_buffer.h:49:35: note:
      'New' has been explicitly marked deprecated here
NODE_EXTERN v8::Local<v8::Object> New(v8::Isolate* isolate,
                                  ^
In file included from ../hello.cc:1:
../node_modules/nan/nan.h:707:26: warning: 'New' is deprecated
      [-Wdeprecated-declarations]
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                         ^
/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0/src/node_buffer.h:41:35: note:
      'New' has been explicitly marked deprecated here
NODE_EXTERN v8::Local<v8::Object> New(v8::Isolate* isolate,
                                  ^
In file included from ../hello.cc:1:
../node_modules/nan/nan.h:733:26: warning: 'Use' is deprecated
      [-Wdeprecated-declarations]
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
                         ^
/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0/src/node_buffer.h:64:35: note:
      'Use' has been explicitly marked deprecated here
NODE_EXTERN v8::Local<v8::Object> Use(v8::Isolate* isolate,
                                  ^
In file included from ../hello.cc:1:
../node_modules/nan/nan.h:868:11: warning: 'FatalException' is deprecated
      [-Wdeprecated-declarations]
    node::FatalException(v8::Isolate::GetCurrent(), try_catch.try_catch_);
          ^
/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0/src/node.h:250:18: note:
      'FatalException' has been explicitly marked deprecated here
NODE_EXTERN void FatalException(v8::Isolate* isolate,
                 ^
In file included from ../hello.cc:1:
../node_modules/nan/nan.h:1776:18: warning: 'Encode' is deprecated
      [-Wdeprecated-declarations]
    return node::Encode(
                 ^
/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0/src/node.h:259:34: note:
      'Encode' has been explicitly marked deprecated here
NODE_EXTERN v8::Local<v8::Value> Encode(v8::Isolate* isolate,
                                 ^
In file included from ../hello.cc:1:
../node_modules/nan/nan.h:1799:16: warning: 'DecodeBytes' is deprecated
      [-Wdeprecated-declarations]
  return node::DecodeBytes(
               ^
/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0/src/node.h:285:21: note:
      'DecodeBytes' has been explicitly marked deprecated here
NODE_EXTERN ssize_t DecodeBytes(v8::Isolate* isolate,
                    ^
In file included from ../hello.cc:1:
../node_modules/nan/nan.h:1819:16: warning: 'DecodeWrite' is deprecated
      [-Wdeprecated-declarations]
  return node::DecodeWrite(
               ^
/Users/antony/.electron-gyp/.node-gyp/iojs-1.5.0/src/node.h:296:21: note:
      'DecodeWrite' has been explicitly marked deprecated here
NODE_EXTERN ssize_t DecodeWrite(v8::Isolate* isolate,
                    ^
../hello.cc:2:10: fatal error: 'regex' file not found
#include <regex>
         ^
15 warnings and 1 error generated.
make: *** [Release/obj.target/hello/hello.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild" "--target=1.5.0" "--arch=x64"
gyp ERR! cwd /Users/antony/home/src/js/electron-cpp-addon
gyp ERR! node -v v7.1.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
$
```

**Comment by kevinsawicki** [comment]
@antonycourtney can you building with node `7.4.0` and the following `.npmrc` file?

```
runtime = electron
disturl = https://atom.io/download/electron
target = 1.5.0
arch = x64
```

**Comment by antonycourtney** [comment]
@kevinsawicki Doesn't seem to make a difference.  When I add that `.npmrc` in the same directory, I get the same result:  `node-gyp rebuild` seems to be build without warnings or errors for node, but `HOME=~/.electron-gyp node-gyp rebuild --target=1.5.0 --arch=x64` fails.

Are you able to clone this repository and reproduce the build error?

**Comment by antonycourtney** [comment]
@kevinsawicki ...sorry; by 'this repository' I mean [https://github.com/antonycourtney/electron-cpp-addon](https://github.com/antonycourtney/electron-cpp-addon)  Tried to make it absolutely minimal and have clear instructions on how to reproduce the problem.

**Comment by kevinsawicki** [comment]
> Tried to make it absolutely minimal and have clear instructions on how to reproduce the problem.

Yeah, I've cloned this repository locally and with that `.npmrc` file at the root of that repository I am able to build with 1.5.0:

```
HOME=~/.electron-gyp npm build .

> hello_world@0.0.0 install /Users/kevin/github/electron-cpp-addon
> node-gyp rebuild

  CXX(target) Release/obj.target/hello/hello.o
  SOLINK_MODULE(target) Release/hello.node
```

I wonder what could be different.

**Comment by kevinsawicki** [comment]
And it does fail for me with 1.4.15:

```
$ HOME=~/.electron-gyp npm build .

> hello_world@0.0.0 install /Users/kevin/github/electron-cpp-addon
> node-gyp rebuild

  CXX(target) Release/obj.target/hello/hello.o
  SOLINK_MODULE(target) Release/hello.node
electron-cpp-addon (master %=)⚡ git fm
Fetching origin
Already up-to-date.
electron-cpp-addon (master %=)⚡ HOME=~/.electron-gyp npm build .

> hello_world@0.0.0 install /Users/kevin/github/electron-cpp-addon
> node-gyp rebuild

  CXX(target) Release/obj.target/hello/hello.o
../hello.cc:2:10: fatal error: 'regex' file not found
#include <regex>
         ^
1 error generated.
make: *** [Release/obj.target/hello/hello.o] Error 1
```

**Comment by antonycourtney** [comment]
@kevinsawicki 

So what do you have in your `~/.electron-gyp/.node-gyp/iojs-1.5.0/common.gypi` at around line 269?  Mine still has:

```
          ['clang==1', {
            'xcode_settings': {
              'GCC_VERSION': 'com.apple.compilers.llvm.clang.1_0',
              'CLANG_CXX_LANGUAGE_STANDARD': 'gnu++0x',  # -std=gnu++0x
            },
          }],
```

(note the missing `CLANG_CXX_LIBRARY`)

**Comment by kevinsawicki** [comment]
@antonycourtney mine has the following around line 387:

```python
['clang==1', {
  'xcode_settings': {
    'GCC_VERSION': 'com.apple.compilers.llvm.clang.1_0',
    'CLANG_CXX_LANGUAGE_STANDARD': 'gnu++0x',  # -std=gnu++0x
    'CLANG_CXX_LIBRARY': 'libc++',
  },
}],
```

**Comment by kevinsawicki** [comment]
@antonycourtney just to confirm, can you completely remove `~/.electron-gyp` and try again?

The file at https://atom.io/download/electron/v1.5.0/iojs-v1.5.0.tar.gz does seem to have the `CLANG_CXX_LIBRARY` in the `common.gypi` file at the root of that archive.

**Comment by antonycourtney** [comment]
@kevinsawicki Ah, I see the problem now.  Transcription error on my end.  My repro instructions inadvertently left out the `--dist-url=https://atom.io/download/electron` argument to the `node-gyp` incantation.  So it was falling back to pulling `https://iojs.org/download/release/v1.5.0/iojs-v1.5.0.tar.gz`, which doesn't have the `CLANG_CXX_LIBRARY` definition.

Many mant thanks for your help and patience; sorry for this mistake testing candidate fix.  Feel free to close issue.

**Comment by kevinsawicki** [comment]
> Many mant thanks for your help and patience; sorry for this mistake testing candidate fix. Feel free to close issue.

Thanks for the update, glad to hear things are working now, closing this out 👍
