### ISSUE TITLE
Cannot build native modules, when include node-canvas

### ISSUE THREAD

**Issue by rikidjava2** [electron/electron#44956]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.0.0

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

I want it build correctly since my project required node-canvas library to run for some feature

### Actual Behavior

Cannot build and hit error when include native-modules node-canvas

### Additional Information

I'm using electron + electron forge,
the command that i use

electron-forge start

but it will failed to start during build the native modules, what is the issue and how i can resolved this.
i can see my electron version & nodejs version should be compatible

Here is the error message

```Project "C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
Building solution configuration "Release|x64".
Project "C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas\build\binding.sln" (1) is building
"C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas\build\canvas-postbuild.vcxproj.metaproj" (2) on node 1 (default targets).
Project "C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas\build\canvas-postbuild.vcxproj.metaproj" (2) is building
"C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas\build\canvas.vcxproj" (3) on node 1 (default targets).
PrepareForBuild:
Creating directory "Release\obj\canvas\".
Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more
details.
Creating directory "Release\obj\canvas\canvas.tlog\".
InitializeBuildStatus:
Creating "Release\obj\canvas\canvas.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
Touching "Release\obj\canvas\canvas.tlog\unsuccessfulbuild".
MakeDirsForCl:
Creating directory "C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas\build\Release\obj\canvas\src\backend".
Creating directory "C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas\build\Release\obj\canvas\src\bmp".
VcpkgTripletSelection:
Using triplet "x64-windows" from "C:\Users\rikim\Documents\appangular\vcpkg\installed\x64-windows\"
Using normalized configuration "Release"
ClCompile:
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\bin\HostX64\x64\CL.exe /c
/I"C:\Users\rikim\.electron-gyp\33.2.1\include\node" /I"C:\Users\rikim\.electron-gyp\33.2.1\src"
/I"C:\Users\rikim\.electron-gyp\33.2.1\deps\openssl\config" /I"C:\Users\rikim\.electron-gyp\33.2.1\deps\openssl\openssl\include"
/I"C:\Users\rikim\.electron-gyp\33.2.1\deps\uv\include" /I"C:\Users\rikim\.electron-gyp\33.2.1\deps\zlib"
/I"C:\Users\rikim\.electron-gyp\33.2.1\deps\v8\include" /I..\..\nan /IC:\GTK\include /IC:\GTK\include\cairo /I"C:\GTK\include\pango-1.0"
/I"C:\GTK\include\glib-2.0" /IC:\GTK\include\freetype2 /I"C:\GTK\lib\glib-2.0\include"
/I"C:\Users\rikim\Documents\appangular\vcpkg\installed\x64-windows\include" /Z7 /nologo /W4 /WX- /diagnostics:column /MP /Ox /Ob2 /Oi /Ot /Oy /GL /D
NODE_GYP_MODULE_NAME=canvas /D USING_UV_SHARED=1 /D USING_V8_SHARED=1 /D V8_DEPRECATION_WARNINGS=1 /D _GLIBCXX_USE_CXX11_ABI=1 /D
ELECTRON_ENSURE_CONFIG_GYPI /D USING_ELECTRON_CONFIG_GYPI /D V8_COMPRESS_POINTERS /D V8_COMPRESS_POINTERS_IN_ISOLATE_CAGE /D V8_31BIT_SMIS_ON_64BIT_ARCH
/D V8_ENABLE_SANDBOX /D WIN32 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _HAS_EXCEPTIONS=0 /D OPENSSL_NO_PINSHARED /D OPENSSL_THREADS /D
OPENSSL_NO_ASM /D _USE_MATH_DEFINES /D NOMINMAX /D BUILDING_NODE_EXTENSION /D "HOST_BINARY=\"node.exe\"" /D _WINDLL /GF /Gm- /EHsc /MT /GS /Gy /fp:precise
/Zc:wchar_t /Zc:forScope /Zc:inline /GR- /Fo"Release\obj\canvas\\src\backend\Backend.obj" /Fd"Release\obj\canvas\vc143.pdb" /external:W4 /Gd /TP /wd4100
/wd4611 /wd4351 /wd4355 /wd4800 /wd4251 /wd4275 /wd4244 /wd4267 /FC /errorReport:queue /Zc:__cplusplus -std:c++20 ..\src\backend\Backend.cc
Backend.cc
C:\Users\rikim\.electron-gyp\33.2.1\include\node\v8-primitive.h(616,62): warning C4324: 'v8::String::ValueView': structure was padded due to alignment
specifier [C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas\build\canvas.vcxproj]
(compiling source file '../src/backend/Backend.cc')

C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(36,23): error C2665: 'v8::ScriptOrigin::ScriptOrigin': no
overloaded function could convert all the argument types [C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas\build\canvas.vcxproj]
(compiling source file '../src/backend/Backend.cc')
C:\Users\rikim\.electron-gyp\33.2.1\include\node\v8-message.h(64,3):
could be 'v8::ScriptOrigin::ScriptOrigin(v8::Local<v8::Value>,int,int,bool,int,v8::Local<v8::Value>,bool,bool,bool,v8::Local<v8::Data>)'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(36,23):
'v8::ScriptOrigin::ScriptOrigin(v8::Local<v8::Value>,int,int,bool,int,v8::Local<v8::Value>,bool,bool,bool,v8::Local<v8::Data>)': cannot convert argument 1
from 'v8::Isolate *' to 'v8::Local<v8::Value>'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(36,47):
'v8::Local<v8::Value>::Local': no overloaded function could convert all the argument types
C:\Users\rikim\.electron-gyp\33.2.1\include\node\v8-local-handle.h(424,1):
could be 'v8::Local<v8::Value>::Local(v8::Local<v8::Value> &&)'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(36,47):
'v8::Local<v8::Value>::Local(v8::Local<v8::Value> &&)': cannot convert argument 1 from 'v8::Isolate *' to 'v8::Local<v8::Value> &&'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(36,47):
Reason: cannot convert from 'v8::Isolate *' to 'v8::Local<v8::Value>'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(36,47):
Conversion requires a second user-defined-conversion operator or constructor
C:\Users\rikim\.electron-gyp\33.2.1\include\node\v8-local-handle.h(424,1):
or       'v8::Local<v8::Value>::Local(const v8::Local<v8::Value> &)'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(36,47):
'v8::Local<v8::Value>::Local(const v8::Local<v8::Value> &)': cannot convert argument 1 from 'v8::Isolate *' to 'const v8::Local<v8::Value> &'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(36,47):
Reason: cannot convert from 'v8::Isolate *' to 'const v8::Local<v8::Value>'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(36,47):
Conversion requires a second user-defined-conversion operator or constructor
C:\Users\rikim\.electron-gyp\33.2.1\include\node\v8-local-handle.h(258,3):
or       'v8::Local<v8::Value>::Local(void)'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(36,47):
'v8::Local<v8::Value>::Local': function does not take 1 arguments
C:\Users\rikim\.electron-gyp\33.2.1\include\node\v8-local-handle.h(261,3):
or       'v8::Local<v8::Value>::Local(v8::Local<S>)'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(36,47):
while trying to match the argument list '(v8::Isolate *)'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(36,23):
while trying to match the argument list '(v8::Isolate *, v8::Local<v8::Value>)'

C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(40,23): error C2665: 'v8::ScriptOrigin::ScriptOrigin': no
overloaded function could convert all the argument types [C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas\build\canvas.vcxproj]
(compiling source file '../src/backend/Backend.cc')
C:\Users\rikim\.electron-gyp\33.2.1\include\node\v8-message.h(64,3):
could be 'v8::ScriptOrigin::ScriptOrigin(v8::Local<v8::Value>,int,int,bool,int,v8::Local<v8::Value>,bool,bool,bool,v8::Local<v8::Data>)'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(40,23):
'v8::ScriptOrigin::ScriptOrigin(v8::Local<v8::Value>,int,int,bool,int,v8::Local<v8::Value>,bool,bool,bool,v8::Local<v8::Data>)': cannot convert argument 1
from 'v8::Isolate *' to 'v8::Local<v8::Value>'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(40,47):
'v8::Local<v8::Value>::Local': no overloaded function could convert all the argument types
C:\Users\rikim\.electron-gyp\33.2.1\include\node\v8-local-handle.h(424,1):
could be 'v8::Local<v8::Value>::Local(v8::Local<v8::Value> &&)'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(40,47):
'v8::Local<v8::Value>::Local(v8::Local<v8::Value> &&)': cannot convert argument 1 from 'v8::Isolate *' to 'v8::Local<v8::Value> &&'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(40,47):
Reason: cannot convert from 'v8::Isolate *' to 'v8::Local<v8::Value>'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(40,47):
Conversion requires a second user-defined-conversion operator or constructor
C:\Users\rikim\.electron-gyp\33.2.1\include\node\v8-local-handle.h(424,1):
or       'v8::Local<v8::Value>::Local(const v8::Local<v8::Value> &)'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(40,47):
'v8::Local<v8::Value>::Local(const v8::Local<v8::Value> &)': cannot convert argument 1 from 'v8::Isolate *' to 'const v8::Local<v8::Value> &'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(40,47):
Reason: cannot convert from 'v8::Isolate *' to 'const v8::Local<v8::Value>'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(40,47):
Conversion requires a second user-defined-conversion operator or constructor
C:\Users\rikim\.electron-gyp\33.2.1\include\node\v8-local-handle.h(258,3):
or       'v8::Local<v8::Value>::Local(void)'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(40,47):
'v8::Local<v8::Value>::Local': function does not take 1 arguments
C:\Users\rikim\.electron-gyp\33.2.1\include\node\v8-local-handle.h(261,3):
or       'v8::Local<v8::Value>::Local(v8::Local<S>)'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(40,47):
while trying to match the argument list '(v8::Isolate *)'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(40,23):
while trying to match the argument list '(v8::Isolate *, v8::Local<v8::Value>, T)'
with
[
T=int
]

C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(47,23): error C2665: 'v8::ScriptOrigin::ScriptOrigin': no
overloaded function could convert all the argument types [C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas\build\canvas.vcxproj]
(compiling source file '../src/backend/Backend.cc')
C:\Users\rikim\.electron-gyp\33.2.1\include\node\v8-message.h(64,3):
could be 'v8::ScriptOrigin::ScriptOrigin(v8::Local<v8::Value>,int,int,bool,int,v8::Local<v8::Value>,bool,bool,bool,v8::Local<v8::Data>)'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(47,23):
'v8::ScriptOrigin::ScriptOrigin(v8::Local<v8::Value>,int,int,bool,int,v8::Local<v8::Value>,bool,bool,bool,v8::Local<v8::Data>)': cannot convert argument 1
from 'v8::Isolate *' to 'v8::Local<v8::Value>'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(47,47):
'v8::Local<v8::Value>::Local': no overloaded function could convert all the argument types
C:\Users\rikim\.electron-gyp\33.2.1\include\node\v8-local-handle.h(424,1):
could be 'v8::Local<v8::Value>::Local(v8::Local<v8::Value> &&)'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(47,47):
'v8::Local<v8::Value>::Local(v8::Local<v8::Value> &&)': cannot convert argument 1 from 'v8::Isolate *' to 'v8::Local<v8::Value> &&'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(47,47):
Reason: cannot convert from 'v8::Isolate *' to 'v8::Local<v8::Value>'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(47,47):
Conversion requires a second user-defined-conversion operator or constructor
C:\Users\rikim\.electron-gyp\33.2.1\include\node\v8-local-handle.h(424,1):
or       'v8::Local<v8::Value>::Local(const v8::Local<v8::Value> &)'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(47,47):
'v8::Local<v8::Value>::Local(const v8::Local<v8::Value> &)': cannot convert argument 1 from 'v8::Isolate *' to 'const v8::Local<v8::Value> &'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(47,47):
Reason: cannot convert from 'v8::Isolate *' to 'const v8::Local<v8::Value>'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(47,47):
Conversion requires a second user-defined-conversion operator or constructor
C:\Users\rikim\.electron-gyp\33.2.1\include\node\v8-local-handle.h(258,3):
or       'v8::Local<v8::Value>::Local(void)'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(47,47):
'v8::Local<v8::Value>::Local': function does not take 1 arguments
C:\Users\rikim\.electron-gyp\33.2.1\include\node\v8-local-handle.h(261,3):
or       'v8::Local<v8::Value>::Local(v8::Local<S>)'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(47,47):
while trying to match the argument list '(v8::Isolate *)'
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(47,23):
while trying to match the argument list '(v8::Isolate *, v8::Local<v8::Value>, T, T)'
with
[
T=int
]

Done Building Project "C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas\build\canvas.vcxproj" (default targets) -- FAILED.
Done Building Project "C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas\build\canvas-postbuild.vcxproj.metaproj" (default targets)
-- FAILED.
Done Building Project "C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas\build\binding.sln" (default targets) -- FAILED.

Build FAILED.

"C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas\build\binding.sln" (default target) (1) ->
"C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas\build\canvas-postbuild.vcxproj.metaproj" (default target) (2) ->
"C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas\build\canvas.vcxproj" (default target) (3) ->
(ClCompile target) ->
C:\Users\rikim\.electron-gyp\33.2.1\include\node\v8-primitive.h(616,62): warning C4324: 'v8::String::ValueView': structure was padded due to alignment
specifier [C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas\build\canvas.vcxproj]


"C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas\build\binding.sln" (default target) (1) ->
"C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas\build\canvas-postbuild.vcxproj.metaproj" (default target) (2) ->
"C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas\build\canvas.vcxproj" (default target) (3) ->
(ClCompile target) ->
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(36,23): error C2665: 'v8::ScriptOrigin::ScriptOrigin': no
overloaded function could convert all the argument types [C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas\build\canvas.vcxproj]
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(40,23): error C2665: 'v8::ScriptOrigin::ScriptOrigin': no
overloaded function could convert all the argument types [C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas\build\canvas.vcxproj]
C:\Users\rikim\Documents\appangular\electron-example\node_modules\nan\nan_scriptorigin.h(47,23): error C2665: 'v8::ScriptOrigin::ScriptOrigin': no
overloaded function could convert all the argument types [C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas\build\canvas.vcxproj]

1 Warning(s)
3 Error(s)

Time Elapsed 00:00:03.59
Error: `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
at ChildProcess.<anonymous> (C:\Users\rikim\Documents\appangular\electron-example\node_modules\@electron\node-gyp\lib\build.js:215:23)
at ChildProcess.emit (node:events:519:28)
at ChildProcess._handle.onexit (node:internal/child_process:294:12)

An unhandled rejection has occurred inside Forge:
Error: node-gyp failed to rebuild 'C:\Users\rikim\Documents\appangular\electron-example\node_modules\canvas'
at ChildProcess.<anonymous> (C:\Users\rikim\Documents\appangular\electron-example\node_modules\@electron\rebuild\lib\module-type\node-gyp\node-gyp.js:121:24)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)```

**Comment by clavin** [comment]
Duplicate of #43510

**Comment by tangjianfang** [comment]
I also encountered a common issue. When I upgraded the Electron version to v32.2.6 or v33.xx, an error occurred while using electron-builder to build usb-detection under Electron.

Reproduction steps: Import usb-detection in electron-quick-start.
### repository：
1. electron-quick-start：https://github.com/electron/electron-quick-start
2. usb-detection：https://github.com/node-usb/node-usb
