### ISSUE TITLE
"A dynamic link library (DLL) initialization routine failed"

### ISSUE THREAD

**Issue by adi518** [electron/electron#10193]
* Electron version: 1.7.5
* Operating system: Win 10

I run my app borderless, so had to require `electron-drag` to re-obtain draggability. It was working with older Electron (`1.4.x`), but now it just fails with the following exception. I done a ton of search and nearly everything points the blame to not rebuilding Electron native Node modules properly. I tried absolutely everything, but to no avail. I'm aware `1.7.5` is tagged pre-release, but hey, it has Chromium 58, which has CSS grids. 👍 

### Actual behavior

```
renderer.js:24 Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\projects\project\node_modules\win-mouse\build\Release\addon.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (C:\projects\project\node_modules\bindings\bindings.js:81:44)
    at Object.<anonymous> (C:\projects\litecloud\node_modules\win-mouse\index.js:3:13)
```

**Comment by MarshallOfSound** [comment]
> I done a ton of search and nearly everything points the blame to not rebuilding Electron native Node modules properly

That is definitely your issue, you should install and run `electron-rebuild`

**Comment by adi518** [comment]
Hi, I already have it. It rebuilds just fine, but the error doesn't go away.

**Comment by MarshallOfSound** [comment]
Can you run it like so

```
set DEBUG=electron-rebuild*
electron-rebuild --force
```

Also please post your `package.json`

**Comment by adi518** [comment]
Output:
```
  inherits: true,
  'readable-stream': true,
  typedarray: true,
  'graceful-fs': true,
  jsonfile: true,
  klaw: true,
  'path-is-absolute': true,
  rimraf: true,
  'fd-slicer': true,
  'pretty-bytes': true,
  'progress-stream': true,
  request: true,
  'single-line-log': true,
  throttleit: true,
  'deep-extend': true,
  ini: true,
  'strip-json-comments': true,
  'es6-promise': true,
  'pinkie-promise': true,
  'core-util-is': true,
  isarray: true,
  'process-nextick-args': true,
  'safe-buffer': true,
  string_decoder: true,
  'util-deprecate': true,
  pend: true,
  speedometer: true,
  through2: true,
  'get-stdin': true,
  meow: true,
  'string-width': true,
  glob: true,
  'aws-sign2': true,
  aws4: true,
  caseless: true,
  'combined-stream': true,
  extend: true,
  'forever-agent': true,
  'form-data': true,
  'har-validator': true,
  hawk: true,
  'http-signature': true,
  'is-typedarray': true,
  isstream: true,
  'json-stringify-safe': true,
  'mime-types': true,
  'oauth-sign': true,
  'performance-now': true,
  qs: true,
  stringstream: true,
  'tough-cookie': true,
  'tunnel-agent': true,
  uuid: true,
  pinkie: true,
  'fs.realpath': true,
  inflight: true,
  minimatch: true,
  once: true,
  'camelcase-keys': true,
  decamelize: true,
  'loud-rejection': true,
  'map-obj': true,
  'normalize-package-data': true,
  'object-assign': true,
  'read-pkg-up': true,
  redent: true,
  'trim-newlines': true,
  xtend: true,
  'code-point-at': true,
  'is-fullwidth-code-point': true,
  'strip-ansi': true,
  'delayed-stream': true,
  asynckit: true,
  ajv: true,
  'har-schema': true,
  boom: true,
  cryptiles: true,
  hoek: true,
  sntp: true,
  'assert-plus': true,
  jsprim: true,
  sshpk: true,
  'mime-db': true,
  punycode: true,
  wrappy: true,
  'brace-expansion': true,
  camelcase: true,
  'currently-unhandled': true,
  'signal-exit': true,
  'hosted-git-info': true,
  'is-builtin-module': true,
  'validate-npm-package-license': true,
  'indent-string': true,
  'strip-indent': true,
  'object-keys': true,
  'find-up': true,
  'read-pkg': true,
  'number-is-nan': true,
  'ansi-regex': true,
  co: true,
  'json-stable-stringify': true,
  extsprintf: true,
  'json-schema': true,
  verror: true,
  asn1: true,
  'bcrypt-pbkdf': true,
  dashdash: true,
  'ecc-jsbn': true,
  getpass: true,
  jsbn: true,
  tweetnacl: true,
  'balanced-match': true,
  'concat-map': true,
  'array-find-index': true,
  repeating: true,
  'builtin-modules': true,
  'spdx-correct': true,
  'spdx-expression-parse': true,
  'load-json-file': true,
  'path-type': true,
  jsonify: true,
  'is-finite': true,
  pify: true,
  'parse-json': true,
  'strip-bom': true,
  'spdx-license-ids': true,
  'error-ex': true,
  'is-utf8': true,
  'is-arrayish': true } +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules +3ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\@types +2ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\acorn-dynamic-import\node_modules +2ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\acorn-globals\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\acorn-jsx\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\are-we-there-yet\node_modules +3ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\asar\node_modules +2ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\babel-loader\node_modules +7ms
\ Searching dependency tree  electron-rebuild scanning: C:\projects\litecloud\node_modules\babel-register\node_modules +9ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\bin-version-check\node_modules +4ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\body-parser\node_modules +2ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\buffer\node_modules +3ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\clean-css\node_modules +6ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\concat-stream\node_modules +3ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\constantinople\node_modules +2ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\dashdash\node_modules +4ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\debug-menu\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\define-properties\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\doctrine\node_modules +2ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\electron-context-menu\node_modules +2ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\electron-packager\node_modules +4ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\electron-packager\node_modules\electron-download\node_modules +0ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\electron-packager\node_modules\fs-extra\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\electron-rebuild\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\eslint\node_modules +5ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\eslint-module-utils\node_modules +15ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\eslint-plugin-import\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\eslint-plugin-node\node_modules +2ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\external-editor\node_modules +5ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\extract-zip\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\fbjs\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\findup-sync\node_modules +2ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\get-package-info\node_modules +4ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\getpass\node_modules +3ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\global\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\grunt\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\grunt-contrib-compass\node_modules +2ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\grunt-contrib-watch\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\grunt-legacy-log\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\grunt-legacy-log-utils\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\grunt-legacy-util\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\inquirer\node_modules +6ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\is-expression\node_modules +4ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\isobject\node_modules +4ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\jsprim\node_modules +5ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\locate-path\node_modules +3ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\matchdep\node_modules +3ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\memory-fs\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\mkdirp\node_modules +4ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\mksnapshot\node_modules +0ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\node-gyp\node_modules +2ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\node-libs-browser\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\node-libs-browser\node_modules\readable-stream\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\node-sass\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\node-soundcloud\node_modules +1ms
| Searching dependency tree  electron-rebuild scanning: C:\projects\litecloud\node_modules\optimist\node_modules +4ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\output-file-sync\node_modules +2ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\pkg-dir\node_modules +5ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\pug-lexer\node_modules +4ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\randomatic\node_modules +4ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\randomatic\node_modules\is-number\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\raw-body\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\readdirp\node_modules +2ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\regjsparser\node_modules +3ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\scss-tokenizer\node_modules +5ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\soundcloud\node_modules +3ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\sshpk\node_modules +4ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\stdout-stream\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\stream-browserify\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\stream-http\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\table\node_modules +4ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\tempfile\node_modules +2ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\tiny-lr\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\touch\node_modules +2ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\uglify-js\node_modules +4ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\unused-filename\node_modules +2ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\url\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\util\node_modules +2ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\verror\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\watchpack\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\webpack\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\with\node_modules +7ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\write\node_modules +1ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\yargs\node_modules +2ms
  electron-rebuild scanning: C:\projects\litecloud\node_modules\yargs-parser\node_modules +0ms
√ Rebuild Complete
```

`package.json`:
```
{
  "name": "litecloud",
  "version": "1.0.0",
  "description": "Soundcloud container",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "install-deps": "bundler & npm i",
    "remove-deps": "timeout 5 && rimraf node_modules",
    "watch": "watch",
    "rebuild": ".\\node_modules\\.bin\\electron-rebuild.cmd",
    "start": "npm run rebuild && electron .",
    "start-offline": "set NODE_ENV=dev&&npm start"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/adi518/litecloud.git"
  },
  "author": "Adi Sahar",
  "license": "GPL-3.0",
  "bugs": {
    "url": "https://github.com/adi518/litecloud/issues"
  },
  "homepage": "https://github.com/adi518/litecloud#readme",
  "dependencies": {
    "electron": "^1.7.5",
    "electron-is-dev": "^0.3.0"
  },
  "devDependencies": {
    "axios": "^0.16.2",
    "babel-cli": "^6.24.1",
    "babel-core": "^6.25.0",
    "babel-eslint": "^7.2.3",
    "babel-loader": "^7.1.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "bemify": "^0.1.2",
    "debounce": "^1.0.2",
    "debug-menu": "^0.6.1",
    "electron-context-menu": "^0.9.1",
    "electron-debug": "^1.3.0",
    "electron-drag": "^1.2.0",
    "electron-packager": "^8.7.2",
    "electron-rebuild": "^1.6.0",
    "eslint": "^4.3.0",
    "eslint-config-airbnb": "^15.1.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-node": "^5.1.1",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-react": "^7.1.0",
    "eslint-plugin-standard": "^3.0.1",
    "grunt": "^1.0.1",
    "grunt-contrib-compass": "^1.1.1",
    "grunt-contrib-pug": "^1.0.0",
    "grunt-contrib-watch": "^1.0.0",
    "jquery": "^3.2.1",
    "lodash": "^4.17.4",
    "matchdep": "^1.0.1",
    "material-design-icons": "^3.0.1",
    "node-sass": "^4.5.3",
    "node-soundcloud": "0.0.6",
    "normalize.css": "^7.0.0",
    "pug": "^2.0.0-rc.3",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-redux": "^5.0.5",
    "redux": "^3.7.2",
    "slash": "^1.0.0",
    "soundcloud": "^3.1.2",
    "throttle-debounce": "^1.0.1",
    "webpack": "^3.4.1"
  }
}
```

**Comment by MarshallOfSound** [comment]
@adi518 `win-mouse` is not a dependency in your package.json so it will not be rebuilt.  Add it as a dependency and run `electron-rebuild` again

**Comment by adi518** [comment]
That's right, because it's a dependency of `electron-drag`.

**Comment by MarshallOfSound** [comment]
@adi518 Which is declared as a devDependency and therefore won't be rebuilt.  It needs to be declared as a production dependency in the `dependencies` section

**Comment by adi518** [comment]
Oh, good one! does this imply I should move all other Electron deps as well?

**Comment by adi518** [comment]
Excellent, it's solved. Thanks so much. 👍

**Comment by MarshallOfSound** [comment]
@adi518 As a general rule for Electron apps, if the dependency is required for the app to run when you distribute it to other people it should be in the `dependencies` section.  If it is only required for developers, you should put it in the `devDependencies` section
