### PR TITLE
fix: sync devtools frontend mime types with upstream

### LINKED ISSUE #25778: Pretty-print JS in devtools doesn't work
To repro:

1. Launch an Electron app (hello world/default fiddle will do)
2. Open DevTools
3. Find a minified JS file, e.g. renderer_init.js
4. Click the "Pretty Print" button in DevTools

Expected behavior:
The JS in the DevTools view is replaced with a pretty-printed version of the code

Actual behavior:
The JS in the DevTools view is unchanged

Bisected to https://github.com/electron/electron/compare/v11.0.0-nightly.20200721...v11.0.0-nightly.20200723

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
Fixes #25778.

This updates the function to match
https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/ui/webui/devtools_ui_data_source.cc;l=52;drc=2de0b2cfe26853bda417346c8a6e6538a06780d8.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed the pretty-print JavaScript feature in DevTools not functioning correctly.

### CODE REVIEW

**Review by codebytere — APPROVED** [review]

**Comment by codebytere** [comment]
think you're missing a header:
````
inlines-hidden -Wno-deprecated-declarations -c ../../electron/shell/browser/ui/devtools_ui.cc -o obj/electron/electron_lib/devtools_ui.o
../../electron/shell/browser/ui/devtools_ui.cc:25:21: error: no member named 'StrCat' in namespace 'base'
  return GURL(base::StrCat({content::kChromeDevToolsScheme,
              ~~~~~~^
1 error generated.
```

**Comment by nornagon** [comment]
whups, fixed locally and forgot to push.
