### ISSUE TITLE
Bootstrap failed at "apm install" in spec

### ISSUE THREAD

**Issue by nantas** [electron/electron#932]
in v0.20.1, Mac OSX 10.10
I'm using nvm for switching node version. The atom-shell repo works in node v0.10.31.

Running `./script/bootstrap.py` give me the following error:

``` bash
dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /path/to/downloaded-atom-shell-repo/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /path/to/downloaded-atom-shell-repo/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node
  Expected in: dynamic lookup

/path/to/downloaded-atom-shell-repo/node_modules/.bin/apm: line 40: 33957 Trace/BPT trap: 5       "$binDir/$nodeBin" --harmony_collections "$binDir/../lib/cli.js" "$@"
Traceback (most recent call last):
  File "script/bootstrap.py", line 123, in <module>
    sys.exit(main())
  File "script/bootstrap.py", line 35, in main
    update_atom_modules('spec')
  File "script/bootstrap.py", line 77, in update_atom_modules
    execute_stdout([apm, 'install'])
  File "/path/to/downloaded-atom-shell-repo/script/lib/util.py", line 148, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['/path/to/downloaded-atom-shell-repo/node_modules/.bin/apm', 'install']' returned non-zero exit status 133

    at ChildProcess.exithandler (child_process.js:732:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1000:16)
    at Socket.<anonymous> (child_process.js:1168:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:461:12)
```

I also tried run
`../node_modules/.bin/apm install` 
in spec directory and the result is the same.
