### ISSUE TITLE
[Bug]: Bump abseil to make it build on glibc 2.34

### ISSUE THREAD

**Issue by darix** [electron/electron#31113]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.4.0

### What operating system are you using?

Other Linux

### Operating System Version

openSUSE Tumbleweed but every distro with glibc 2.34 is affected e.g. ubuntu 21.10

### What arch are you using?

x64

### Expected Behavior

nodejs compiles

### Actual Behavior

it doesnt compile because of 

https://github.com/abseil/abseil-cpp/issues/957

https://github.com/abseil/abseil-cpp/issues/952

### Additional Information

It would be nice if this is also fixed for 13.x when you release this fix

https://github.com/electron/electron/pull/31091

**Comment by darix** [comment]
similar issue in

```
third_party/breakpad/breakpad/src/client/linux/handler/exception_handler.cc:141:49: error: no matching function for call to 'max(int, long int)'
```
