### ISSUE TITLE
[Bug]: After updating electron from 13.6.9 to 14.0.0, I am getting errors in Google Analytics.

### ISSUE THREAD

**Issue by HarunoOi** [electron/electron#33465]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.1

### What operating system are you using?

macOS

### Operating System Version

mac OS mojave 10.14.6, Windows10 21H2

### What arch are you using?

x64

### Last Known Working Electron version

13.6.9

### Expected Behavior

Information can still be sent to Google Alanytics.

### Actual Behavior

No information is sent to Google Alanytics at all.

When debugging was run using analytics_debug.js, the following error was output.

```
analytics_debug.js:31 Error: type={0: "exc", 1: "create", 2: "TypeError"} method= message= account=log @ analytics_debug.js:31
analytics_debug.js:31 Called method ""create"" threw exception: TypeError: Cannot destructure property 'app' of 'remote' as it is undefined.
```

I had the same error before, and that time I added an "enableRemoteModule: true" and it was fixed.

I thought it was necessary to take action to remove the REMORE module, but I'm not sure where to rewrite it.
I wrote a trial version, but it is not work.
https://github.com/electron/remote/blob/main/README.md#migrating-from-remote

main_window.js
```
const GoogleAnalyticsWindow = require('../../../google_analytics_window')
module.exports = class SphereWindow {
  ...
  createWindow() {
    ...
    this.window.webContents.on('did-finish-load', () => {
      ...
      this.gaWindow = new GoogleAnalyticsWindow()
    })
    this.render(`${this.viewsPath}/main_window_show.html.ejs`)
  }
  ...
}
```

google_analytics_window.js
```
  constructor() {
    require('@electron/remote/main').initialize()
    this.window= new BrowserWindow({ 
        show: true, //対応完了後falseに戻す
        webPreferences : {
          enableRemoteModule: true,
          contextIsolation: false,
          nodeIntegration:true,
          preload: path.resolve(path.join(__dirname, 'RicohTheta/javascripts/main/preload_modules/google_analytics_send_modules.js'))
        }
      })// initialize
    require('@electron/remote/main').enable(this.window.webContents);
    this.window.loadURL(`file://${path.join(__dirname, "views", "google_analytics_send.html.ejs")}`)
    this.window.webContents.on('did-finish-load', () => {
      
      this.window.webContents.send('create-tracker', GoogleAnalyticsWindow.trackingId)
    })
  }
```

google_analytics_send_modules.js
```
const electron = require('electron');
global.ipc = electron.ipcRenderer;
global.electronCookies = require('@exponent/electron-cookies')
```

google_analytics_send.html.ejs
```
<!DOCTYPE html>
<html>
<head>
  <script src="../views/assets/vendor/jquery-2.2.4.js"></script>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics_debug.js','ga'); 

    'use strict'
    const ipc = window.ipc;
    const ElectronCookies = window.electronCookies
    ElectronCookies.enable({ origin: 'https://example.com' }) 
    const { BrowserWindow } = require("@electron/remote")

    ipc.on ('create-tracker', (e, options) => {
      window.ga_debug = {trace: true}; 
      ga('create', options.trackingId, 'auto')
    })

    ipc.on ('screen', (e, field) => {
      ga('set', 'checkProtocolTask', null)
      ga('set', 'appName', field.appName)
      ga('set', 'appVersion', field.appVersion)
      ga('send', 'screenview', {'screenName': field.screenName})
    })

    ipc.on ('event', (e, field) => {
      ga('send', 'event', field.category, field.action, field.label)
    })
  </script>
</head>
<body>
</body>
```

### Additional Information
node module'@exponent/electron-cookies' use `let { app } = remote;`.
Here's where the error occurs.

**Comment by HarunoOi** [comment]
use heap/electron-cookies instead of @exponent/electron-cookies.
