### ISSUE TITLE
TypeError: process.electronBinding is not a function when using initialize from @electron/remote/main

### ISSUE THREAD

**Issue by SubliemeSiem** [electron/electron#26643]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v11.0.2, with @electron/remote v1.0.0
* **Operating System:**
  * Windows 10 (1803)
* **Last Known Working Electron version:**
  * 10.1.2, with @electron/remote v1.0.0

### Expected Behavior
Calling ```require('@electron/remote/main').initialize();``` in main.js should not produce any errors.

### Actual Behavior
When running ```electron .``` the following error is thrown:
```
TypeError: process.electronBinding is not a function
    at Object.<anonymous> (C:\Projects\msal electron poc\node_modules\@electron\remote\dist\src\main\objects-registry.js:3:24)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12694)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Projects\msal electron poc\node_modules\@electron\remote\dist\src\main\server.js:8:44)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
```

### To Reproduce
Simply include ```require('@electron/remote/main').initialize();``` at the top of your main.js. I tried creating a fiddle, but it hangs on ```Installing node modules using npm: @electron/remote/main...```

### Example project
at https://github.com/SubliemeSiem/electron-bug-example
```
npm i
npm start
```
Shows the error. Change the electron version to 10.1.2 and run ```npm i``` and ```npm start``` again and the error disappears.

**Comment by ckerr** [comment]
Confirmed: https://github.com/SubliemeSiem/electron-bug-example works in v10.1.6 but not v11.0.2 on Ubuntu 20.04.

**Comment by nornagon** [comment]
Please file this issue on https://github.com/electron/remote.

**Comment by nornagon** [comment]
In fact, this looks like a duplicate of https://github.com/electron/remote/issues/15.
