### ISSUE TITLE
BrowserView autoResize doesn't work correctly in some cases and BrowserView shrinks

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#22174]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 7.1.2 (also in 5.0.7 and 4.0.0; haven't tested earlier)
* **Operating System:** Windows 10

### Expected Behavior
I have a `BrowserView` that is configured to resize with the window. I have a `resize` handler on the `BrowserWindow` that in some cases calls `setBounds`/`setSize` to change the size of the window.

I expect the `BrowserView` to resize with the window.

### Actual Behavior
The `BrowserView` doesn't resize correctly and shrinks.

### To Reproduce
Download the quickstart app. Replace main.js with:

```
const { app, BrowserWindow, BrowserView } = require('electron')

async function createWindow() {
  const mainWindow = new BrowserWindow({ backgroundColor: "#000" });
  const view = new BrowserView();
  mainWindow.setBrowserView(view);

  const contentBounds = mainWindow.getContentBounds();
  view.setBounds({ x: 0, y: 0, width: contentBounds.width, height: contentBounds.height });
  view.setAutoResize({ width: true, height: true });

  await view.webContents.loadURL("https://google.com");

  mainWindow.once("maximize", () => {
    mainWindow.once("resize", () => {
      mainWindow.setSize(1000, 1000);
      setTimeout(() => {
        console.log(mainWindow.getBounds()); // logs what it used to be at {x: 914, y: 62, width: 800, height: 600}
        console.log(view.getBounds()); // bounds are not resized correctly: {x: 0, y: 0, width: 0, height: 145}
      }, 1000);
    });
  });
}

app.on('ready', createWindow)
```

Run `npm start`, maximize the window to set up the `resize` handler, and then unmaximize it.

Observe all the black space in the window where you would expect to see the browser view (google).

### Gif
![browserview_resize_issue](https://user-images.githubusercontent.com/6374473/74377426-7a023c00-4da9-11ea-919a-708560c81d78.gif)

**Comment by pushkin-** [comment]
looks like setting `horizontal: true`, `vertical: true` in the `setAutoResize` options makes the effect less bad, but if you expand the window, there are still black bars on the edges.

**Comment by pushkin-** [comment]
Wrapping the `setSize` call in a `setTimeout(, 0)` works around the issue

**Comment by pushkin-** [comment]
@sofianguy FYI, this is also an issue in Electron 8. Thanks

**Comment by pushkin-** [comment]
Still a problem in Electron 10.1.2

**Comment by pablo1v** [comment]
Same in 12.0.1.

**Comment by qparas** [comment]
use this
this works

```
function createWindow() {
  // Create the browser window.
  const mainWindow = new BrowserWindow({ useContentSize: true });
  const view = new BrowserView();
  mainWindow.setBrowserView(view);
  view.setBounds({ x: 0, y: 0, width: 800, height: 600 });
  view.setAutoResize({ width: true, height: true });
  view.webContents.loadURL("https://youtube.com");
}
```

**Comment by pushkin-** [comment]
@qparas What is the piece that makes this work exactly? I am basically doing this already except for the `useContentSize` property, which I don't want to use.

**Comment by qparas** [comment]
> @qparas What is the piece that makes this work exactly? I am basically doing this already except for the `useContentSize` property, which I don't want to use.

yes the "{ useContentSize: true }" part

**Comment by chase** [comment]
@codebytere Your PR #34581 fixes the case where `setBounds` is called on a view, but not when AutoResize is called.

Using this change, I made a temporary fix in my project that basically forces the layout/paint by setting the bounds to the ones returned by `getBounds`.

``` javascript
const mainWindow = new BrowserWindow({ backgroundColor: "#000" });
const view = new BrowserView();
mainWindow.setBrowserView(view);

const contentBounds = mainWindow.getContentBounds();
view.setBounds({ x: 0, y: 0, width: contentBounds.width, height: contentBounds.height });
view.setAutoResize({ width: true, height: true });

let lastHandle;
function handleWindowResize(e) => {
  e.preventDefault();
  
  // the setTimeout is necessary because it runs after the event listener is handled
  lastHandle = setTimeout(() => {
    if (lastHandle != null) clearTimeout(lastHandle);
    view.setBounds(view.getBounds());
  });
};

mainWindow.on("resize", handleWindowResize);
```

As this is the case, I believe that by adding these lines:
https://github.com/electron/electron/blob/02a5d6cb55a76f491ca7833ec3c05de391900661/shell/browser/native_browser_view_views.cc#L133-L137

after this line:
https://github.com/electron/electron/blob/02a5d6cb55a76f491ca7833ec3c05de391900661/shell/browser/native_browser_view_views.cc#L112

should fix this issue, or at least ones similar to it.

**Comment by safinaskar** [comment]
@chase , your code fixed my issue, thanks! (in my code autoResize didn't work with maximize, now it works). Also I used usual Electron 20.0.2 without additional patches

**Comment by pushkin-** [comment]
repros in Electron 21

**Comment by glocore** [comment]
@chase's fix seems to work for me only when the `BrowserView` spans the whole width and height of the window. My app has some "chrome" around the `BrowserView`, and I'm getting the same weird effect when resizing the window (Electron v21). As a workaround, I've been setting the position and dimensions manually inside of the window's `resize` handler instead. I've tested this only on macOS; it seems smooth and performant.

```ts
const mainWindow = new BrowserWindow();
const view = new BrowserView();
mainWindow.addBrowserView(view);

view.setBounds({
  x: 0,
  y: 36,
  width: mainWindow.getBounds().width,
  height: mainWindow.getBounds().height - 36,
});

view.webContents.loadURL("https://electronjs.org");

let lastHandle;
function handleWindowResize(e) {
  e.preventDefault();

  // the setTimeout is necessary because it runs after the event listener is handled
  lastHandle = setTimeout(() => {
    if (lastHandle != null) clearTimeout(lastHandle);
    if (mainWindow)
      view.setBounds({
        x: 0,
        y: 36,
        width: mainWindow.getBounds().width,
        height: mainWindow.getBounds().height - 36,
      });
  });
}

mainWindow.on("resize", handleWindowResize);
```

**Comment by pushkin-** [comment]
bump

**Comment by ferreira-tb** [comment]
Still an issue in v23.1.3

**Comment by Nebula-Developer** [comment]
> Wrapping the `setSize` call in a `setTimeout(, 0)` works around the issue

That fixed it for the mean time, thanks a bunch.

**Comment by safinaskar** [comment]
bump

**Comment by lucabytes** [comment]
For me this works:

```
mainWindow.once('maximize', () => {
   const wb = mainWindow.getBounds();
   view.setBounds({ x: 0, y: 0, width: wb.width, height: wb.height });
});
```

where view has just width auto-resize
```
view.setAutoResize({
   width: true,
});
```

**Comment by safinaskar** [comment]
Still reproducible with Node 18.13, Electron 26.2, recent Debian Linux sid.

To reproduce the bug resize the window, then maximize, then unmaximize, then again resize, etc. At some moment you will see that BrowserView's size is wrong

**Comment by michaelyohanes** [comment]
bump

**Comment by courtsimas** [comment]
bump

**Comment by thorsent** [comment]
Looks like BV auto resizing is broken in Electron 30. We're seeing two behaviors: (1) vertical resizing of parent isn't being respected, (2) vertical and horizontal dimensions shrink when the parent window's top/left are changed without height/width changing - i.e. when moving a window (smells like an off by one pixel issue).

WebContentsView doesn't seem to support auto-resize which is an unfortunate loss :( The BV's auto-resizing is very smooth by comparison.

https://github.com/electron/electron/assets/1657084/4bcb5065-8934-4869-8668-338b1c27fd90

**Comment by linonetwo** [comment]
Regression:

1. Property 'setAutoResize' does not exist on type 'WebContentsView'.ts(2339)
2. (method) Electron.BaseWindow.getContentView(): void  (Returns View - The content view of the window. Shouldn't be void)

**Comment by thorsent** [comment]
Bump, still an issue in 31 and 32. This is becoming critical as 29 will soon no longer be supported.

**Comment by nikitakot** [comment]
bump

**Comment by yangannyx** [comment]
> 1. Property 'setAutoResize' does not exist on type 'WebContentsView'.ts(2339)
> 2. BrowserView autoResize doesn't work after upgrade from 29 to 31
> 3. (method) Electron.BaseWindow.getContentView(): void (Returns View - The content view of the window. Shouldn't be void)

cc @linonetwo

Added a ticket to track adding setAutoResize to WebContentsView [here](https://github.com/electron/electron/issues/43802)

BrowserView not resizing correctly is fixed by [this PR](https://github.com/electron/electron/pull/43637) in 31.6.0, 32.1.0, and 33.0.0-alpha4.

Haven't looked at getContentView returning void, but might be worth having a separate issue for

**Comment by linonetwo** [comment]
@yangannyx Thank you, do you know where I can edit the typing? I can't search where `electron.d.ts` is generated from https://github.com/search?q=repo%3Aelectron%2Felectron%20getContentView&type=code

**Comment by linonetwo** [comment]
I haven't test it yet, any one know if it is fixed?

**Comment by linonetwo** [comment]
<img width="992" alt="Image" src="https://github.com/user-attachments/assets/6ba28c60-aeb4-4cab-b1d1-0dcbd9c30ba3" />

Seems not fixed?

**Comment by nikitakot** [comment]
this workaround works perfectly for me in the electron 33

```ts
...
const view = new BrowserView(options);
browserWindow.addBrowserView(view);
const [width, height] = browserWindow.getContentSize();
view.setBounds({ x: 0, y: 0, width, height }); // fill the entire main window
...
browserWindow.on('resize', () => {
     const [width, height] = browserWindow.getContentSize();
     view.setBounds({ x: 0, y: 0, width, height });
});
```
