### ISSUE TITLE
Build failed with "older compiler than other objects" error

### ISSUE THREAD

**Issue by steem** [electron/electron#12622]
Sync the trunk code, then:
1. python script\bootstrap.py -v --target_arch=ia32
2. python script\build.py

Got the following error:
FAILED: D:\Python27\python.exe gyp-win-tool link-with-manifests environment.x86 True node.dll "D:\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /IMPLIB:node.dll.lib /DLL /OUT:node.dll @node.dll.rsp" 2 mt.exe rc.exe "obj\vendor\node\node_lib.node.dll.intermediate.manifest" obj\vendor\node\node_lib.node.dll.generated.manifest
fatal error C1047: The object or library file 'obj\vendor\node\src\node_lib.async_wrap.obj' was created with an older compiler than other objects; rebuild old objects and libraries
LINK : fatal error LNK1257: code generation failed

Python is 2.7 and vs version is 2017. OS is Win10 64bit.

How to fix it?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by steem** [comment]
Ok. It's ok now after updating visual studio 2017 version to 15.6.6.
