### PR TITLE
docs: mention app ready event for DevTools Extension tutorial

### PR DESCRIPTION
**Pull request by Starefossen**
Just attempted to install the React DevTools following this tutorial and kept getting `TypeError: BrowserWindow.addDevToolsExtension is not a function` error message when attempting to load the extension. Had to dig into the API docs before I found that this particular API is not available before the app ready event has been called. Would be nice to newcomers to have that information right on the tutorial.

On an other note, I did not get the relative `~` path working on macOS 10.11.6 and Electron 1.3.0 and had to use the full path `/Users/me/Library/...` before the extension loaded successfully. Might be worth mentioning?

### CODE REVIEW

**Comment by zcbenz** [comment]
Thanks!
