### ISSUE TITLE
Cannot find module '../box-layout'

### ISSUE THREAD

**Issue by burtonator** [electron/electron#13930]
* Electron Version: 3.0.0-beta4
* Operating System (Platform and Version): Ubuntu 18.0.4
* Last known working Electron version: 

2.0.5

I'm getting the following exception after upgrading to 3.0 and using Spectron:

```
     unknown error: Cannot find module '../box-layout'
Error: Cannot find module '../box-layout'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/burton/projects/polar-bookshelf/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.get [as BoxLayout] (/home/burton/projects/polar-bookshelf/node_modules/electron/dist/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at EventEmitter.<anonymous> (/home/burton/projects/polar-bookshelf/node_modules/electron/dist/resources/electron.asar/browser/rpc-server.js:274:70)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/home/burton/projects/polar-bookshelf/node_modules/electron/dist/resources/electron.asar/browser/api/web-contents.js:287:13)
    at WebContents.emit (events.js:182:13)
  Error: An unknown server-side error occurred while processing the command.
      at execute(<Function>, "require") - api.js:73:26

```

.. I'm going to  try to track this down as I need to be on 3.0 as 2.x has a crash bug that's been fixed in 3.0.

**Comment by dsabanin** [comment]
Seeing the same thing on macOS 10.14 Beta (18A353d), Electron 3.0.0-beta4, electron-chromedriver 3.0.0-beta.1 and spectron 3.8.0.
