### ISSUE TITLE
Electron failed to build on Windows due to error LNK2019: unresolved external symbol

### ISSUE THREAD

**Issue by KarenHuang2016** [electron/electron#9548]
Electron failed to build on Windows with VS2015 Update 3. This issue can be repro from master branch revision [3f4abc6](https://github.com/electron/electron/commit/3f4abc6323717ab1158b193b44996eb783cab203) . Could you please take a look at this? Thanks in advance!

How to reproduce:
1. git clone https://github.com/electron/electron.git D:\Electron\src
2. Open a clean command prompt and browse to D:\Electron
3. python script\bootstrap.py -v --target_arch=ia32
4. vendor\depot_tools\ninja.exe -C out\R electron -v -d keeprsp

Acutal result:
electron_lib.lib(electron_lib.node_debugger.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) class v8::Platform * __cdecl v8::platform::CreateDefaultPlatform(int)" (__imp_?CreateDefaultPlatform@platform@v8@@YAPAVPlatform@2@H@Z) referenced in function "public: void __thiscall atom::NodeDebugger::Start(void)" (?Start@NodeDebugger@atom@@QAEXXZ)
electron.exe : fatal error LNK1120: 1 unresolved externals

**Comment by brenca** [comment]
Can confirm. The debug build seems to be OK, only release builds are affected.

**Comment by khwaaj** [comment]
I can confirm as well. I get the same unresolved symbol on both macOS and Windows, anyone figured out the reason yet?

**Comment by kevinsawicki** [comment]
This might be related to https://github.com/electron/libchromiumcontent/pull/291, will investigate.

**Comment by khwaaj** [comment]
Sounds plausible since the missing symbol is in v8_libplatform according to my digging.

**Comment by alespergl** [comment]
@kevinsawicki Yes, seem [this change](https://github.com/electron/electron/commit/a33643c51849d6026b65a5641ff6dda4ffcd55ba#diff-f2ef646527d2d648ff80506b929d11fdR30) introduced dependency on v8::platform from `electron.exe` which would cause this linker error. The hiding of v8::platform from `node.dll` was based on the assumption that it's not called from outside of that DLL. If that's not the case anymore, it can be exposed.

**Comment by kevinsawicki** [comment]
@alespergl okay, thanks, I'll revert the libcc change for now.

**Comment by TimNZ** [comment]
@kevinsawicki Related? OS X, Electron 1.7.1

➜  electron git:(master) ./script/build.py       
ninja: Entering directory `out/R'
[1335/1348] SOLINK "Electron Framework.framework/Versions/A/Electron Framework", POSTBUILDS
FAILED: ../../vendor/llvm-build/Release+Asserts/bin/clang++ -shared -ObjC -stdlib=libc++ -Wl,-dead_strip -mmacosx-version-min=10.9 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -arch x86_64 -L. -install_name @rpath/Electron\ Framework.framework/Electron\ Framework -Wl,-rpath,@loader_path/Libraries -F/Users/timshnaider/Desktop/Development/electron/electron/external_binaries -stdlib=libc++ -o "Electron Framework.framework/Versions/A/Electron Framework" @Electron_Framework.framework.rsp
Undefined symbols for architecture x86_64:
  "_ppdOpenFile", referenced from:
      printing::ParsePpdCapabilities(base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, printing::PrinterSemanticCapsAndDefaults*) in libchromiumcontent.a(cups_helper.o)
  "_ppdMarkDefaults", referenced from:
      printing::ParsePpdCapabilities(base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, printing::PrinterSemanticCapsAndDefaults*) in libchromiumcontent.a(cups_helper.o)
  "_ppdErrorString", referenced from:
      printing::ParsePpdCapabilities(base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, printing::PrinterSemanticCapsAndDefaults*) in libchromiumcontent.a(cups_helper.o)
  "_cupsParseOptions", referenced from:
      printing::ParsePpdCapabilities(base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, printing::PrinterSemanticCapsAndDefaults*) in libchromiumcontent.a(cups_helper.o)
  "_cupsMarkOptions", referenced from:
      printing::ParsePpdCapabilities(base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, printing::PrinterSemanticCapsAndDefaults*) in libchromiumcontent.a(cups_helper.o)
  "_ppdLastError", referenced from:
      printing::ParsePpdCapabilities(base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, printing::PrinterSemanticCapsAndDefaults*) in libchromiumcontent.a(cups_helper.o)
  "_ppdFindAttr", referenced from:
      printing::ParsePpdCapabilities(base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, printing::PrinterSemanticCapsAndDefaults*) in libchromiumcontent.a(cups_helper.o)
  "_ppdFindOption", referenced from:
      printing::ParsePpdCapabilities(base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, printing::PrinterSemanticCapsAndDefaults*) in libchromiumcontent.a(cups_helper.o)
  "_ppdFindChoice", referenced from:
      printing::ParsePpdCapabilities(base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, printing::PrinterSemanticCapsAndDefaults*) in libchromiumcontent.a(cups_helper.o)
  "_httpError", referenced from:
      printing::PrintBackendCUPS::GetPPD(char const*) in libchromiumcontent.a(print_backend_cups.o)
  "_httpClose", referenced from:
      printing::HttpConnectionCUPS::~HttpConnectionCUPS() in libchromiumcontent.a(cups_helper.o)
  "_ppdClose", referenced from:
      printing::ParsePpdCapabilities(base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, printing::PrinterSemanticCapsAndDefaults*) in libchromiumcontent.a(cups_helper.o)
  "_httpConnectEncrypt", referenced from:
      printing::HttpConnectionCUPS::HttpConnectionCUPS(GURL const&, http_encryption_e) in libchromiumcontent.a(cups_helper.o)
  "_cupsFreeDests", referenced from:
      printing::PrintBackendCUPS::EnumeratePrinters(std::__1::vector<printing::PrinterBasicInfo, std::__1::allocator<printing::PrinterBasicInfo> >*) in libchromiumcontent.a(print_backend_cups.o)
      printing::PrintBackendCUPS::GetDefaultPrinterName() in libchromiumcontent.a(print_backend_cups.o)
      printing::PrintBackendCUPS::GetPrinterBasicInfo(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, printing::PrinterBasicInfo*) in libchromiumcontent.a(print_backend_cups.o)
      printing::PrintBackendCUPS::GetPrinterDriverInfo(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libchromiumcontent.a(print_backend_cups.o)
      printing::PrintBackendCUPS::IsValidPrinter(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libchromiumcontent.a(print_backend_cups.o)
  "_cupsGetPPD", referenced from:
      printing::PrintBackendCUPS::GetPPD(char const*) in libchromiumcontent.a(print_backend_cups.o)
  "_cupsGetDests", referenced from:
      printing::PrintBackendCUPS::GetDests(cups_dest_s**) in libchromiumcontent.a(print_backend_cups.o)
  "_ppdFindMarkedChoice", referenced from:
      printing::ParsePpdCapabilities(base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, printing::PrinterSemanticCapsAndDefaults*) in libchromiumcontent.a(cups_helper.o)
  "_httpBlocking", referenced from:
      printing::HttpConnectionCUPS::SetBlocking(bool) in libchromiumcontent.a(cups_helper.o)
  "_cupsLastError", referenced from:
      printing::PrintBackendCUPS::EnumeratePrinters(std::__1::vector<printing::PrinterBasicInfo, std::__1::allocator<printing::PrinterBasicInfo> >*) in libchromiumcontent.a(print_backend_cups.o)
      printing::PrintBackendCUPS::GetPPD(char const*) in libchromiumcontent.a(print_backend_cups.o)
  "_cupsGetNamedDest", referenced from:
      printing::PrintBackendCUPS::GetNamedDest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libchromiumcontent.a(print_backend_cups.o)
  "v8::platform::CreateDefaultPlatform(int)", referenced from:
      atom::NodeDebugger::Start() in libelectron_lib.a(electron_lib.node_debugger.o)
  "_cupsGetDests2", referenced from:
      printing::PrintBackendCUPS::GetDests(cups_dest_s**) in libchromiumcontent.a(print_backend_cups.o)
  "_cupsGetPPD2", referenced from:
      printing::PrintBackendCUPS::GetPPD(char const*) in libchromiumcontent.a(print_backend_cups.o)
  "_cupsFreeOptions", referenced from:
      printing::ParsePpdCapabilities(base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, printing::PrinterSemanticCapsAndDefaults*) in libchromiumcontent.a(cups_helper.o)
  "_cupsGetOption", referenced from:
      printing::(anonymous namespace)::PrinterBasicInfoFromCUPS(cups_dest_s const&, printing::PrinterBasicInfo*) in libchromiumcontent.a(print_backend_cups.o)
      printing::PrintBackendCUPS::GetPrinterDriverInfo(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libchromiumcontent.a(print_backend_cups.o)
  "_cupsGetDest", referenced from:
      printing::PrintBackendCUPS::GetDefaultPrinterName() in libchromiumcontent.a(print_backend_cups.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by khwaaj** [comment]
I've seen this too but it is a separate issue. Adding -lcups in brightray/brightray.gyp for OS == mac makes the build work, but i don't know it it is the "correct" solution here.

**Comment by TimNZ** [comment]
@khwaaj Thanks.  That fixed my error, now just get the original issue error, so will pull latest.

**Comment by kevinsawicki** [comment]
> Related? OS X, Electron 1.7.1

Thanks so much for reporting this @TimNZ , I believe this was probably caused by #8596, we only run release builds on CI when we go to release since linking takes so long so thanks for helping us catch this earlier, fix is up at https://github.com/electron/electron/pull/9579

> Adding -lcups in brightray/brightray.gyp for OS == mac makes the build work, but i don't know it it is the "correct" solution here.

I think this is the correct solution 👍
