### ISSUE TITLE
1.4.12 not work with node 6.9.2

### ISSUE THREAD

**Issue by keyiis** [electron/electron#8234]
* Electron version:1.4.12 ia32 win32
* Operating system:win10 x64

### Expected behavior

should work well

### Actual behavior
`Uncaught TypeError: Error.captureStackTrace is not a function`
![qq 20161218141913](https://cloud.githubusercontent.com/assets/7766085/21303366/f0ae95f6-c5f8-11e6-8639-4ce6d190ac58.jpg)

### How to reproduce
bindings.js:126 
```
Error.captureStackTrace(dummy)
  dummy.stack
```
**about bindings.js**
```
node-bindings
=============
### Helper module for loading your native module's .node file

This is a helper module for authors of Node.js native addon modules.
It is basically the "swiss army knife" of `require()`ing your native module's
`.node` file.

Throughout the course of Node's native addon history, addons have ended up being
compiled in a variety of different places, depending on which build tool and which
version of node was used. To make matters worse, now the _gyp_ build tool can
produce either a _Release_ or _Debug_ build, each being built into different
locations.

This module checks _all_ the possible locations that a native addon would be built
at, and returns the first one that loads successfully.
```

i used node 6.9.2 x64 to devloper.

**Comment by kevinsawicki** [comment]
`Error.captureStackTrace` should be available in Electron 1.4.12. Could a library or some part of your application be removing it?

Can you run the electron default app and confirm it is available there for you?

![screen shot 2016-12-19 at 9 24 36 am](https://cloud.githubusercontent.com/assets/671378/21322240/103e3ace-c5cd-11e6-8fd1-342f1d0cf7e2.png)

**Comment by keyiis** [comment]
@kevinsawicki default app available for me,but what,s library or some part of application be removing it?

**Comment by kevinsawicki** [comment]
@keyiis can you provide the application you are using?

**Comment by keyiis** [comment]
@kevinsawicki i think the cause is webpack,not electron,thanks reply!
