### ISSUE TITLE
webContents::send doesn't work on parameter unpacking since 1.3.2

### ISSUE THREAD

**Issue by zhengshencn** [electron/electron#6753]
* Electron version: 1.3.2
* Operating system: Windown 10

Hi,

I have the following code to pass variant length of variables list via IPC from main process to render process. It works well until we upgrade prebuilt from 1.3.1 to 1.3.2.

```
handler.webContents.on('did-finish-load', () => {
    handler.webContents.send.apply(this, args);
});
```

I got the following exception
```
TypeError: this._send is not a function
    at WebContents.send (C:\apps\electron-v1.3.2-win32-x64\resources\electron.asar\browser\api\web-contents.js:92:15)
```

Could you please let me know if this is by design intent, or a bug?

Thanks!

**Comment by MarshallOfSound** [comment]
@zhengshencn 

The code you supplied is invalid, you are rebinding the `webContents` send method to an object that isn't a `webContents`.  Therefore when it is called and it attempts to do `this._send` it isn't there (the function was rebound)

This code should work

```js
handler.webContents.on('did-finish-load', () => {
    handler.webContents.send.apply(handler.webContents, args);
});
``` 

Although I would question why you need to call `.apply` anyway as this code would do the job as well

```js
handler.webContents.on('did-finish-load', () => {
    handler.webContents.send(args);
});
```

**Comment by zhengshencn** [comment]
@MarshallOfSound  Thank you very much for your reply. I'm pretty sure I've tried  handler.webContents.send.apply(handler.webContents, args); but it failed for a different reason (I don't have my laptop with me, will update by tomorrow). 
I don't have strong reason to unpack parameter here this way. It's simply because it looks better to me comparing to using argument array :-) (I used to use this way a lot with other script language, like python).

**Comment by MarshallOfSound** [comment]
@zhengshencn Take a look at my preferred way again

```js
handler.webContents.on('did-finish-load', () => {
    handler.webContents.send(...args);
});
```

The **`...`** automatically spreads array values across the function arguments.  See [the docs](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Spread_operator)

**Comment by zhengshencn** [comment]
@MarshallOfSound You are right. I didn't read through your reply carefully enough. Thank you!

**Comment by hellosaumil** [comment]
[powerMonitor.on('on-battery', function () {
     console.log('The system is on-battery power!');
    webContents.send('power', {
        message: 'The machine is running on battery power, yo!'
    });
});](url)

This throws as error : [Uncaught TypeError: webContents.send is not a function](url)
