### ISSUE TITLE
jQuery delegated .on method does not work

### ISSUE THREAD

**Issue by akashwoz** [electron/electron#8274]
* Electron version: 1.4.13
* Operating system: Windows 7 x64

It does work on browser but doesn't seem to work on electron, I've tried jQuery 2.0.2 and 3.1.1, both of them throw this error on electron but the browser doesn't, I suppose this is a bug or what am I doing wrong? I'm no pro in JavaScript

A delegated .on throws this error when called:
`Uncaught TypeError: W[g].exec is not a function`

### How to reproduce

Call a delegated `.on` on any element, like
```
$("#blah").on("click", "#bleh", function(){
    console.log("merp");
});
```
It should probably throw an error. 
Thanks

**Comment by MarshallOfSound** [comment]
@akashwoz I attempted to reproduce this in `electron-quick-start` using this fiddle

https://jsfiddle.net/druw23f8/

Unfortunately this did not throw the error you described.  It sounds like you are using a different third-party library that is throwing this error.  Can you provide a minimal application /code sample that reproduces this issue?

**Comment by akashwoz** [comment]
@MarshallOfSound Well it's a music player I made for myself, the files are dynamically added to a `div` like this
```
for (var i = 0; i < fileArray.length; i++) {
     $('#playlist').append('<div id="playlist-audio" source="' + fileArray[i] + '">' + path.basename(fileArray[i]) + '</div>');
}
```

and for the child element's delegated click

```
$('#playlist').on("click", "#playlist-audio", function(){
    var musicSource = $(this).attr('source');
    player.src = musicSource;
});
```

and when the element inside the `#playlist` is clicked it is supposed to change the player's `src`, but all it does is throw that error, I'm only using `jsmediatags`, only one third party library but the thrown error is from the jquery file at line 2, as seen in this screenshot

![image](https://cloud.githubusercontent.com/assets/20661194/21455125/c14ad862-c943-11e6-99c2-e7e0c37e07d7.png)

**Comment by akashwoz** [comment]
I figured a way for event delegation without jQuery and it works without any error like that, but I'd really love to know how to "fix" that jQuery exception

**Comment by kevinsawicki** [comment]
> I figured a way for event delegation without jQuery and it works without any error like that, but I'd really love to know how to "fix" that jQuery exception

Can you try without a minified jQuery version and get a better stack trace?

**Comment by kevinsawicki** [comment]
Closing out until more information is available.

This looks like an issue with jQuery or one of the other project dependencies being used, using a non-minified version should help debug it. Looks like something that is expected to be a regex isn't and it can't call `exec` on that object.

Placing a breakpoint there in the dev tools will allow you to inspect what `W[g]` is when that function is called and may help track down why this error is being thrown.
