### PR TITLE
fix: ensure ready-to-show event is fired

### PR DESCRIPTION
**Pull request by codebytere**
Backport of #25632

See that PR for details.

Notes: Fix ready-to-show event not emitted on some machines.

### CODE REVIEW

**Comment by ckerr** [comment]
FTBFS:

```
FAILED: obj/electron/electron_lib/electron_api_web_contents.o 
/home/builduser/project/build-tools/third_party/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/electron/electron_lib/electron_api_web_contents.o.d -DV8_DEPRECATION_WARNINGS -DGDK_DISABLE_DEPRECATION_WARNINGS -DGLIB_DISABLE_DEPRECATION_WARNINGS -DDCHECK_ALWAYS_ON=1 -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -DCR_CLANG_REVISION=\"n346557-4e0d9925-2\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -D_LIBCPP_DEBUG=0 -DCR_LIBCXX_REVISION=375504 -DCR_SYSROOT_HASH=813389c0526b816233ee4a5c041d45c98a4ba791 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DV8_USE_EXTERNAL_STARTUP_DATA -DNODE_WANT_INTERNALS=1 -DELECTRON_PRODUCT_NAME=\"Electron\" -DELECTRON_PROJECT_NAME=\"electron\" -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_40 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_40 -DENABLE_IPC_FUZZER -DWEBP_EXTERN=extern -DVK_NO_PROTOTYPES -DGL_GLEXT_PROTOTYPES -DUSE_GLX -DUSE_EGL -DTOOLKIT_VIEWS=1 -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DUCHAR_TYPE=uint16_t -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DSK_USER_CONFIG_HEADER=\"../../skia/config/SkUserConfig.h\" -DSK_GL -DSK_CODEC_DECODES_JPEG -DSK_ENCODE_JPEG -DSK_USE_LIBGIFCODEC -DSK_VULKAN_HEADER=\"../../skia/config/SkVulkanConfig.h\" -DSK_VULKAN=1 -DSK_SUPPORT_GPU=1 -DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\" -DVK_NO_PROTOTYPES -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_LINUX -DABSL_ALLOCATOR_NOTHROW=1 -DWEBRTC_USE_BUILTIN_ISAC_FIX=0 -DWEBRTC_USE_BUILTIN_ISAC_FLOAT=1 -DWEBRTC_USE_X11 -DHAVE_SCTP -DNO_MAIN_THREAD_WRAPPING -DCRASHPAD_ZLIB_SOURCE_EXTERNAL -DLEVELDB_PLATFORM_CHROMIUM=1 -DLEVELDB_PLATFORM_CHROMIUM=1 -DATK_LIB_DIR=\"/usr/lib/x86_64-linux-gnu\" -DUSE_ATK_BRIDGE -DATK_DISABLE_DEPRECATION_WARNINGS -DV8_COMPRESS_POINTERS -DV8_31BIT_SMIS_ON_64BIT_ARCH -DV8_DEPRECATION_WARNINGS -DUSE_VULKAN_XLIB -DV8_COMPRESS_POINTERS -DV8_31BIT_SMIS_ON_64BIT_ARCH -DV8_DEPRECATION_WARNINGS -DHAVE_INSPECTOR=1 -DHAVE_OPENSSL=1 -DOPENSSL_NO_SSL_TRACE=1 -DNODE_HAVE_I18N_SUPPORT=1 -DNODE_USE_V8_PLATFORM=0 -D_POSIX_C_SOURCE=200112 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I../../electron/chromium_src -I../../electron -Igen/electron -I../../third_party/blink/renderer -I../.. -Igen -I../../electron -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -I../../third_party/libyuv/include -I../../third_party/jsoncpp/source/include -I../../third_party/jsoncpp/generated -I../../third_party/libwebp/src -Igen/third_party/dawn/src/include -I../../third_party/dawn/src/include -I../../third_party/khronos -I../../gpu -I../../third_party/vulkan/include -I../../third_party/boringssl/src/include -I../../third_party/ced/src -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/skia -I../../third_party/libgifcodec -I../../third_party/vulkan/include -I../../third_party/skia/third_party/vulkanmemoryallocator -I../../third_party/vulkan/include -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/protobuf/src -I../../third_party/webrtc_overrides -I../../third_party/webrtc -Igen/third_party/webrtc -I../../third_party/abseil-cpp -I../../third_party/crashpad/crashpad -I../../third_party/crashpad/crashpad/compat/non_mac -I../../third_party/crashpad/crashpad/compat/linux -I../../third_party/crashpad/crashpad/compat/non_win -I../../third_party/zlib -I../../third_party/libwebm/source -I../../third_party/leveldatabase -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase/src/include -I../../v8/include -Igen/v8/include -Igen/third_party/metrics_proto -Igen -Igen/components/policy/proto -I../../third_party/re2/src -I../../third_party/mesa_headers -Igen -Igen -Igen -Igen -I../../v8/include -Igen/v8/include -I../../third_party/electron_node/src -I../../third_party/electron_node/deps/uv/include -I../../v8/include -I../../third_party/breakpad/breakpad/src -Igen -Igen -Igen -Igen -I../../third_party/flatbuffers/src/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -B../../third_party/binutils/Linux_x64/Release/bin -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -fcomplete-member-pointers -m64 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -Wall -Werror -Wextra -Wimplicit-fallthrough -Wunreachable-code -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wno-pointer-to-int-cast -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g1 -ftrivial-auto-var-init=pattern -fvisibility=hidden -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/gio-unix-2.0 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/libmount -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/blkid -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/glib-2.0 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/glib-2.0 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wno-shorten-64-to-32 -Wno-header-guard -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/nss -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/nspr -Wno-unused-function -Wno-unused-local-typedef -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/atk-1.0 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/at-spi2-atk/2.0 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/at-spi-2.0 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/dbus-1.0 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/lib/x86_64-linux-gnu/dbus-1.0/include -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/glib-2.0 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/dbus-1.0 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/lib/x86_64-linux-gnu/dbus-1.0/include -Wno-microsoft-include -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/gdk-pixbuf-2.0 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/libmount -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/blkid -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/glib-2.0 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/gtk-3.0 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/at-spi2-atk/2.0 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/at-spi-2.0 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/dbus-1.0 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/lib/x86_64-linux-gnu/dbus-1.0/include -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/gtk-3.0 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/gio-unix-2.0 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/cairo -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/libdrm -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/pango-1.0 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/harfbuzz -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/pango-1.0 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/fribidi -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/atk-1.0 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/cairo -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/pixman-1 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/uuid -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/freetype2 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/libpng16 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/gdk-pixbuf-2.0 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/libmount -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/blkid -isystem../../build/linux/debian_sid_amd64-sysroot/usr/include/glib-2.0 -isystem../../build/linux/debian_sid_amd64-sysroot/usr/lib/x86_64-linux-gnu/glib-2.0/include -std=c++14 -fno-exceptions -fno-rtti -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include --sysroot=../../build/linux/debian_sid_amd64-sysroot -fvisibility-inlines-hidden -Wno-deprecated-declarations -c ../../electron/shell/browser/api/electron_api_web_contents.cc -o obj/electron/electron_lib/electron_api_web_contents.o
../../electron/shell/browser/api/electron_api_web_contents.cc:1212:7: error: use of undeclared identifier 'receivers_'
  if (receivers_.current_context() == web_contents()->GetMainFrame()) {
      ^
1 error generated.
```

**Comment by codebytere** [comment]
ah, rip - think this might require mojo tweaking

**Comment by zcbenz** [comment]
Maybe we do not need to backport this to 9-x-y? https://github.com/electron/electron/issues/25253 says the event was working on 9.0.0.
