### PR TITLE
fix: inspector context menu throwing an error

### PR DESCRIPTION
**Pull request by codebytere**
#### Description of Change

Fixes an issue where right-clicking on the inspector throws an error:

```
[84035:0601/000704.374553:ERROR:CONSOLE(57)] "Uncaught (in promise) Error: Error invoking remote method 'INSPECTOR_CONTEXT_MENU': TypeError: e._getURL is not a function", source: electron/js2c/sandbox_bundle.js (57)
Error occurred in handler for 'INSPECTOR_CONTEXT_MENU': TypeError: e._getURL is not a function
    at assertChromeDevTools (electron/js2c/browser_init.js:177:881)
    at electron/js2c/browser_init.js:177:1127
    at new Promise (<anonymous>)
    at electron/js2c/browser_init.js:177:1117
    at electron/js2c/browser_init.js:197:579
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10150)
    at Object.emit (events.js:376:20)
 ```
 
 Tested by running a stock Fiddle and right-clicking in the devtools console.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixes an issue where right-clicking in the devtools console throws an error

### CODE REVIEW

**Review by MarshallOfSound — APPROVED** [review]

**Comment by MarshallOfSound** [comment]
This only needs to go to 14 as it was caused by https://github.com/electron/electron/pull/28839

**Review by deepak1556 — APPROVED** [review]

**Review by nornagon — APPROVED** [review]
