### ISSUE TITLE
React Devtools can't connect in v5.0.0

### ISSUE THREAD

**Issue by wellbeck190** [electron/electron#17586]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version: 5.0.0-beta.6**
* **Operating System: macOS Mojave**
* **Last Known Working Electron version: 4.0.0**

### Expected Behavior

React Devtools 3.6.0 work well in Electron v5.0.0
### To Reproduce

Open BrowserWindow with url point to a react page ( in my case, react page has been created by create-react-app)

### Screenshots

<img width="804" alt="Screen Shot 2019-03-28 at 6 43 35 AM" src="https://user-images.githubusercontent.com/26106557/55119942-6a90ea80-5126-11e9-9ace-6859bbb64c02.png">

### Additional Information
Terminal output
```
Attempted to load extension "React Developer Tools" that has already been loaded.
2019-03-28 06:39:19.922 electron[26697:1164642] *** WARNING: Textured window <EventDispatchingWindow: 0x7fe65dca97d0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
[26697:0328/063944.495011:ERROR:CONSOLE(19)] "Uncaught TypeError: chrome.tabs.create is not a function", source: chrome-extension://react-developer-tools/build/panel.js (19)
[26697:0328/064024.449538:ERROR:CONSOLE(28)] "failed to connect", source: chrome-extension://react-developer-tools/build/panel.js (28)
```

```
Uncaught TypeError: chrome.tabs.create is not a function
```
I guest have bug when support chrome api
Thanks.

**Comment by Nimelrian** [comment]
Can confirm in beta 7. Neither the React nor the Redux devtools can hook into their respective libraries.

**Comment by scherzocrk** [comment]
can confirm on beta 7 too
