### ISSUE TITLE
app.setAppPath is not a function

### ISSUE THREAD

**Issue by mgc** [electron/electron#9439]
* Electron version: 1.6.8
* Operating system: Mac 10.12.4

### Behavior
We had a user report the following dialog after a Squirrel update from Electron 1.6.3 to 1.6.8:
![image](https://cloud.githubusercontent.com/assets/66737/25968937/085e0d66-3648-11e7-92b6-ec6909bf9d37.png)

This appears to be a regression from https://github.com/electron/electron/pull/9095 ? 

### How to reproduce
Unclear. It hasn't happened on subsequent app restarts, so perhaps it was related to the update process?

**Comment by mgc** [comment]
Per @kevinsawicki this must be an updater issue. `getPath` is called a line earlier, and exported in the same way as `setAppPath`. This means we somehow ended up with the 1.6.8 asar content talking to the 1.6.3 electron runtime, which is *extremely* confusing.

**Comment by syonip** [comment]
@mgc how did you end up solving this?

**Comment by syonip** [comment]
OK, I noticed that in my case too the old file persisted through the updating process, because it was locked by the anti-virus software on the machine, thus creating an old version+new version mix.

Thanks.

**Comment by mgc** [comment]
@syonip interesting, was this also on a mac? We've only seen it happen once, and it was on a mac with Sophos installed.

**Comment by syonip** [comment]
No, I've only seen it happen on a 32-bit windows 7 machine.
When manually trying to remove my app's main exe file, I noticed the anti-virus software was blocking it's removal.
Restarting the machine allowed me to delete the old exe file.
