### ISSUE TITLE
Windows 10 build fails  

### ISSUE THREAD

**Issue by CSharpFan** [electron/electron#12061]
* Electron version: 53229e3d6c544c68137497ed09a074250c1af0fc, master, latest as of 2/26/2018
* Operating system: Windows 10, 1709, x64
* Python 2.7.14 x64 installed
* Visual Studio 2015 Update 3 Enterprise installed & fully up2date
* Node.js 6.9.0 through nvm

### Expected behavior

Build should work

### Actual behavior

Build doesn't work, get following error:
```
PS C:\__SOURCES\electron> python script\build.py
ninja: Entering directory `out\R'
[871/1225] CXX obj\vendor\node\src\node.node_api.obj
c:\__sources\electron\vendor\node\src\node_api.cc(261): warning C4309: 'static_cast': truncation of constant value
c:\__sources\electron\vendor\node\src\node_api.cc(1004): warning C4309: 'static_cast': truncation of constant value
c:\__sources\electron\vendor\node\src\node_api.cc(1037): warning C4309: 'static_cast': truncation of constant value
c:\__sources\electron\vendor\node\src\node_api.cc(1264): warning C4309: 'static_cast': truncation of constant value
c:\__sources\electron\vendor\node\src\node_api.cc(1288): warning C4309: 'static_cast': truncation of constant value
c:\__sources\electron\vendor\node\src\node_api.cc(1309): warning C4309: 'static_cast': truncation of constant value
c:\__sources\electron\vendor\node\src\node_api.cc(1604): warning C4309: 'static_cast': truncation of constant value
c:\__sources\electron\vendor\node\src\node_api.cc(1727): warning C4309: 'static_cast': truncation of constant value
c:\__sources\electron\vendor\node\src\node_api.cc(1731): warning C4309: 'static_cast': truncation of constant value
c:\__sources\electron\vendor\node\src\node_api.cc(1741): warning C4309: 'static_cast': truncation of constant value
c:\__sources\electron\vendor\node\src\node_api.cc(1743): warning C4309: 'static_cast': truncation of constant value
c:\__sources\electron\vendor\node\src\node_api.cc(2003): warning C4309: 'static_cast': truncation of constant value
c:\__sources\electron\vendor\node\src\node_api.cc(2022): warning C4309: 'static_cast': truncation of constant value
c:\__sources\electron\vendor\node\src\node_api.cc(2041): warning C4309: 'static_cast': truncation of constant value
[875/1225] CXX obj\vendor\node\src\node.node.obj
c:\__sources\electron\vendor\node\src\node.cc(3434): warning C4129: 'd': unrecognized character escape sequence
c:\__sources\electron\vendor\node\src\node.cc(3434): warning C4129: 'e': unrecognized character escape sequence
c:\__sources\electron\vendor\node\src\node.cc(3438): warning C4129: 'd': unrecognized character escape sequence
c:\__sources\electron\vendor\node\src\node.cc(3438): warning C4129: 'e': unrecognized character escape sequence
c:\__sources\electron\vendor\node\src\node.cc(3446): warning C4129: 'd': unrecognized character escape sequence
c:\__sources\electron\vendor\node\src\node.cc(3446): warning C4129: 'e': unrecognized character escape sequence
[1205/1225] LINK_EMBED(DLL) node.dll
FAILED: C:\Python27\python.exe gyp-win-tool link-with-manifests environment.x64 True node.dll "C:\Python27\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /IMPLIB:node.dll.lib /DLL /OUT:node.dll @node.dll.rsp" 2 mt.exe rc.exe "obj\vendor\node\node.node.dll.intermediate.manifest" obj\vendor\node\node.node.dll.generated.manifest
error C2220: warning treated as error - no 'executable' file generated
warning C4743: 'const std::bad_weak_ptr::`vftable'' has different size in 'c:\build\src\out-x64\static_library\gen\out-x64\static_library\gen\v8\src\inspector\inspector_jumbo_1.cc' and 'c:\__sources\electron\vendor\node\src\node_platform.cc': 24 and 16 bytes
LINK : fatal error LNK1257: code generation failed
Traceback (most recent call last):
  File "gyp-win-tool", line 323, in <module>
    sys.exit(main(sys.argv[1:]))
  File "gyp-win-tool", line 29, in main
    exit_code = executor.Dispatch(args)
  File "gyp-win-tool", line 71, in Dispatch
    return getattr(self, method)(*args[1:])
  File "gyp-win-tool", line 179, in ExecLinkWithManifests
    subprocess.check_call(ldcmd + add_to_ld)
  File "C:\Python27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Python27\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /IMPLIB:node.dll.lib /DLL /OUT:node.dll @node.dll.rsp node.dll.manifest.res' returned non-zero exit status 1257
ninja: build stopped: subcommand failed.
```

### How to reproduce
```
git clone https://github.com/electron/electron.git
python script\bootstrap.py -v
python script\build.py
```

**Comment by MarshallOfSound** [comment]
I see you've got a fresh clone in your repro steps but just wanted to check you've tried this from a clean checkout?

**Comment by CSharpFan** [comment]
That's correct, I delete everything, and then do a `git checkout .`.

**Comment by kwonoj** [comment]
I just rebased `master` TOT and experiencing same. It was fine around yesterday's tot when I tried, quick peeking commit history https://github.com/electron/electron/commit/f7786a9e4829183cb4eab93fad06a958193f099c this might be related? (yes, it's quite vague speculation, sorry)

**Comment by ah4ap** [comment]
I have the same issue on the f7786a9 and 1.8.2 versions of the electron.
I continue to look for a way to completely build it, but my ideas are over...

- MVS Pro 2015 update 3
- Win10 Pro x64 build 16299
- Python 2.7.14 x64
- Node.js v8.9.4

**Comment by CSharpFan** [comment]
`warning C4743: 'const std::bad_weak_ptr::`vftable'' has different size in 'c:\build\src\out-x64\static_library\gen\out-x64\static_library\gen\v8\src\inspector\inspector_jumbo_1.cc' and 'c:\__sources\electron\vendor\node\src\node_platform.cc': 24 and 16 bytes` feels like different padding or x64 vs x86?

**Comment by ah4ap** [comment]
I have a little confuse because I cannot find the definition of this constant in the specified file: ...\vendor\node\src\node_platform.cc
And nothing that have same name like this constant

**Comment by ckerr** [comment]
This failure appears to be coming from encountering warnings when compiling Node 8.9.4 with -Werror turned on.

I notice that @codebytere has a PR at https://github.com/electron/electron/pull/12101 to update Node to 9.7.0, so I'm wondering if that will move this bug forward as a side-effect...

**Comment by bughit** [comment]
Is there some flaw with the CI that this is allowed to happen? When I was doing a pull request I could not get a line that's too long past the linter, so how does a failure to build get through to master? It does not build on windows?

**Comment by bughit** [comment]
Node 9.7.0 does not resolve this. 

@zcbenz is this warning safe to ignore?, If so, how?

**Comment by bughit** [comment]
I tried bughit/electron@6c7e4bcc01c2eaa64bb9c39142e99ecba7e90e46 to ignore the warning, didn't work.

**Comment by felixrieseberg** [comment]
I have no trouble building. My setup: `npm i -g windows-build-tools`, as well as Visual Studio 2015 with Update 3 (Community Edition).

**Comment by bughit** [comment]
Why would one need build tools and vs? vs and python should be sufficient?

It looks like people here are not using build tools but vs pro and above.

I can try community in a different vm, can you try without the build tools (considering build directions don't include them)?

**Comment by bughit** [comment]
I noticed that "Common Tools for Visual C++" feature was unchecked (though installed) in vs setup, and [remained unchecked after checking and installing it again] (https://social.msdn.microsoft.com/Forums/sqlserver/en-US/a5aadafc-b335-4e72-b3b0-a165627f29ec/problem-with-installation-common-tools-c-for-visual-studio-2015-community).  Any one else experiencing this?

I am going to try to uninstall vs pro and try with just the [build tools](http://download.microsoft.com/download/5/F/7/5F7ACAEB-8363-451F-9425-68A90F98B238/visualcppbuildtools_full.exe).

@felixrieseberg Which windows sdk is needed?  Build tools install 8.1 by default.

**Comment by bughit** [comment]
It does not build with just the tools: ValueError: Could not locate Visual Studio installation.

@felixrieseberg Why are you recommending tools & vs?

- reinstalled vs2015 pro to get rid of unchecked Common Tools for Visual C++ issue. Build still failed, I did not copy the error.
- installed `npm i -g windows-build-tools`
  - I am not sure it installed anything but python (which I would not be using since a different one is already in the path). the log had entries like
    - MUX:  Stop Block: CommunityBlock : Visual Studio 2015 is currently installed on this machine. Please uninstall Visual Studio 2015 and retry.
    - Exit code: 0x80044000, restarting: No
  - And yet it may have messed something up because the build starting using the x86 cross compiler
    - C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64_x86\cl.exe
    - and failed differently (Front end and back end not compatible (must target same processor)
       ```
       FAILED: C:\Python27\python.exe gyp-win-tool link-with-manifests environment.x86 True node.dll "C:\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /IMPLIB:node.dll.lib /DLL /OUT:node.dll @node.dll.rsp" 2 mt.exe rc.exe "obj\vendor\node\node_lib.node.dll.intermediate.manifest" obj\vendor\node\node_lib.node.dll.generated.manifest fatal error C1905: Front end and back end not compatible (must target same processor).
       ```
  - Though not certain if it was already doing that before the build tools install
  - I started forcing --target_arch x64, which is now failing as before:
    warning C4743: 'const std::bad_weak_ptr::`vftable'' has different size

**Comment by bughit** [comment]
A full clean took care of the wrong compiler selection.  Not clear why.  Also installed community.

So the bottom line, there are no signs that there's anything wrong with my system.

- I met all software prereqs (now with community)
- I am doing a clean release build of master and 1-8-x, following directions to the letter
- 1-8-x succeeds
- master fails with warning C4743: 'const std::bad_weak_ptr::`vftable'' has different size
- other people are experiencing this

**Comment by felixrieseberg** [comment]
Here's the thing: I _do_ think that there's something off with your system, we just don't know what exactly it is - but we should figure it out, document it, and help you out!

**Comment by zcbenz** [comment]
I used to have weird errors from Visual Studio when upgrading from 2013 to 2015, and I had to install WDK/Windows 8.1 SDK in right order otherwise compilation would blow. I ended up with reinstalling my Windows box and carefully followed instructions to install Visual Studio. I also heard from other developers of bad things when they installed Visual Studio 2015 and 2017 together.

The versions of Visual Studio, and the order you installed them could all contribute to this weird problem, I'm sorry but the simplest fix is probably reinstalling Windows and everything.

You can also wait for the `upgrade-to-chromium-63` branch, which we moved to Visual Studio 2017 for building, it might have this problem fixed (or introduced other bugs).

**Comment by bughit** [comment]
I have 2013 and 2015 installed. I'm creating a new win7 vm.

I couple of suggestions for the build system that may avoid these issues.

* A mode where the build instead of looking for vs, would be provided the base path to the build-tools which could be
  * from vs
  * from vs build tools
* Allow the specification of the Windows SDK

So even if there's something wrong with vs, you could always install separate build tools and SDK and point to those.

**Comment by bughit** [comment]
I built a new win7 vm from scratch and the same problem is there

Here's the only software installed:

- win7 ent sp1 x64 fully patched by ms update (including optional, excluding 2018.2 Preview of Monthly Rollup)
- VMware Tools
- Chrome 65 x64
- git 2.16.2 x64
- python 2.7.1.4 (default download was x86)
- node 9.8.0 x64
- notepad++ x86 7.5.5
- vs 2015 update 3 community (iso downloaded from ms)
  - en_visual_studio_community_2015_with_update_3_x86_x64_dvd_8923300.iso
  - sha1: C838DF0D2DAD6E763DF5A7974F5FFCD45B98FD0E
  - installed with only one feature: Common Tools for Visual C++ 2015

> I do think that there's something off with your system

@felixrieseberg The above system can't get any cleaner or plainer.

error:

```
ninja: Entering directory `out\R'
[1149/1229] LINK_EMBED(DLL) node.dll
FAILED: C:\Python27\python.exe gyp-win-tool link-with-manifests environment.x64 True node.dll "C:\Python27\python.exe gyp-win-tool l
ink-wrapper environment.x64 False link.exe /nologo /IMPLIB:node.dll.lib /DLL /OUT:node.dll @node.dll.rsp" 2 mt.exe rc.exe "obj\vendo
r\node\node_lib.node.dll.intermediate.manifest" obj\vendor\node\node_lib.node.dll.generated.manifest
error C2220: warning treated as error - no 'executable' file generated
warning C4743: 'const std::bad_weak_ptr::`vftable'' has different size in 'c:\build\src\out-x64\static_library\gen\out-x64\static_li
brary\gen\v8\src\inspector\inspector_jumbo_1.cc' and 'c:\src\electron\vendor\node\src\node_platform.cc': 24 and 16 bytes
LINK : fatal error LNK1257: code generation failed
Traceback (most recent call last):
  File "gyp-win-tool", line 323, in <module>
    sys.exit(main(sys.argv[1:]))
  File "gyp-win-tool", line 29, in main
    exit_code = executor.Dispatch(args)
  File "gyp-win-tool", line 71, in Dispatch
    return getattr(self, method)(*args[1:])
  File "gyp-win-tool", line 179, in ExecLinkWithManifests
    subprocess.check_call(ldcmd + add_to_ld)
  File "C:\Python27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Python27\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /IMP
LIB:node.dll.lib /DLL /OUT:node.dll @node.dll.rsp node.dll.manifest.res' returned non-zero exit status 1257
[1149/1229] CXX obj\atom\browser\osr\electron_lib.osr_web_contents_view.obj
ninja: build stopped: subcommand failed.
```

**Comment by bughit** [comment]
@felixrieseberg @zcbenz

>  but we should figure it out, document it, and help you out

Your build directions currently don't work on a clean win7 vm (also on win10, per the OP)  If it's working for you, you are doing something more or different or more specific than your public directions. Your help is needed to figure out what.

**Comment by bughit** [comment]
@zcbenz I take it this will not be investigated because of upgrade-to-chromium-63, is that right?

In that case approximately when is upgrade-to-chromium-63 planned to be merged?  Days? Weeks?

**Comment by zcbenz** [comment]
@bughit Currently our focus is on upgrade-to-chromium-63 so no one is looking into this for now. You can track the progress at https://github.com/electron/electron/projects/7, I don't really want to give estimate since it would stress others, but we do not have much tasks left.

**Comment by andens** [comment]
For what it's worth, I have had this error and tried to find where it was introduced. Building worked for cc608a3fb0cc6eb5f4d575ab2fdae4ddb888f41f, but started showing the error when https://github.com/electron/electron/pull/11230 was merged in the next commit.

However, https://github.com/electron/electron/pull/11459 was merged while I was tinkering so I figured that I'd try that one as well and it also works. It seems that whatever happened with Chromium 62 was subsequently fixed in Chromium 63.

**Comment by bughit** [comment]
yes, master release build is now working with vs2017

#11230 was merged 23 days ago, so for this long master was not buildable. Would be nice if you had something to catch this. A build on a clean win7 vm, following your public instructions, would have done it.

**Comment by miniak** [comment]
Please re-open if you are still experiencing issues with builds.
